namespace ApogeeVGC.Sim.Core;

public enum DriverMode
{
    // Interactive modes
    ConsoleVsRandom,
    GuiVsRandom,

    // Parallel random-team evaluation
    RndVsRndEvaluation,

    // MCTS vs Random evaluation
    MctsVsRndEvaluation,

    // Greedy vs Random evaluation
    GreedyVsRndEvaluation,

    // Standalone MCTS (heuristic eval, uniform priors) vs Random evaluation
    MctsStandaloneVsRndEvaluation,

    // MCTS with DL models (policy priors + value eval, no info tracking) vs Random evaluation
    MctsDlVsRndEvaluation,

    // DL-Greedy (argmax policy, no search) vs Random — isolates model quality from search
    DlGreedyVsRndEvaluation,

    // Showdown live assist — WebSocket server for Tampermonkey overlay, policy + value inference
    ShowdownAssist,

    // Deterministic regression test — runs fixed battles across formats, prints hash
    DeterministicRegressionTest,

    /// <summary>
    /// Runs a single battle with 5 specific seeds for debugging purposes.
    /// Useful for reproducing failures from RndVsRndEvaluation.
    /// </summary>
    SingleBattleDebug,

    /// <summary>
    /// Verify Gen5RNG port matches Showdown's PRNG output.
    /// Compare with: node Tools/EquivalenceTest/gen5rng_test.js
    /// </summary>
    Gen5RngVerification,

    /// <summary>
    /// Replay a Showdown fixture through C# and compare protocol output.
    /// Requires fixture JSON + Showdown log generated by run_showdown_battle.js.
    /// </summary>
    EquivalenceTest,
}
