namespace ApogeeVGC.Sim.Core;

public enum DriverMode
{
    // Interactive modes
    ConsoleVsRandom,
    GuiVsRandom,

    // Parallel random-team evaluation
    RndVsRndEvaluation,

    // MCTS vs Random evaluation
    MctsVsRndEvaluation,

    // Greedy vs Random evaluation
    GreedyVsRndEvaluation,

    // Standalone MCTS (heuristic eval, uniform priors) vs Random evaluation
    MctsStandaloneVsRndEvaluation,

    // MCTS with DL models (policy priors + value eval, no info tracking) vs Random evaluation
    MctsDlVsRndEvaluation,

    // DL-Greedy (argmax policy, no search) vs Random — isolates model quality from search
    DlGreedyVsRndEvaluation,

    // Showdown live assist — WebSocket server for Tampermonkey overlay, policy + value inference
    ShowdownAssist,

    /// <summary>
    /// Runs a single battle with 5 specific seeds for debugging purposes.
    /// Useful for reproducing failures from RndVsRndEvaluation.
    /// </summary>
    SingleBattleDebug,

    /// <summary>
    /// Runs a single MCTS-DL vs Random battle with verbose decision logging.
    /// At every decision point, prints all legal actions with DL policy priors,
    /// MCTS visit counts, Q-values, and the final selected action.
    /// Edit seed constants in Driver.Debug.cs to reproduce specific battles.
    /// </summary>
    MctsDlSingleBattleDebug,

    /// <summary>
    /// Verify Gen5RNG port matches Showdown's PRNG output.
    /// Compare with: node Tools/EquivalenceTest/gen5rng_test.js
    /// </summary>
    Gen5RngVerification,

    /// <summary>
    /// Replay a Showdown fixture through C# and compare protocol output.
    /// Requires fixture JSON + Showdown log generated by run_showdown_battle.js.
    /// Use for debugging specific seeds that fail in the EquivalenceBatchTests xUnit test.
    /// </summary>
    EquivalenceTest,

    /// <summary>
    /// Automated Showdown battler: connects to play.pokemonshowdown.com via WebSocket,
    /// authenticates, searches for VGC ladder games, and plays using DL-Greedy.
    /// Logs full battle transcripts and structured results for thesis analysis.
    /// Configure via showdown_config.json.
    /// </summary>
    ShowdownBattler,

    /// <summary>
    /// Bot-vs-bot evaluation: runs N battles between any two player types using the internal
    /// simulator. Outputs structured JSON results for the automated pipeline.
    /// CLI args: --player1, --player2, --battles, --mcts-iterations, --threads, --output
    /// </summary>
    Evaluate,
}
