using System.Text.Json;
using ApogeeVGC.LiveAssist;
using ApogeeVGC.Sim.BattleClasses;
using ApogeeVGC.Sim.FormatClasses;
using ApogeeVGC.Sim.PokemonClasses;
using ApogeeVGC.Sim.SideClasses;
using ApogeeVGC.Sim.Utils;

namespace ApogeeVGC.Sim.Core;

public partial class Driver
{
    /// <summary>
    /// Verify that Gen5Rng produces identical output to Showdown's Gen5RNG.
    /// Run the JS counterpart (Tools/EquivalenceTest/gen5rng_test.js) and compare output.
    /// </summary>
    public static void RunGen5RngVerification()
    {
        Console.WriteLine("=== Gen5RNG Verification ===");
        Console.WriteLine("Compare output with: node Tools/EquivalenceTest/gen5rng_test.js\n");

        var seed = new Gen5RngSeed(1, 2, 3, 4);

        // Test raw next() values
        var rng = new Gen5Rng(seed);
        Console.WriteLine("=== Raw next() values (100) ===");
        for (var i = 0; i < 100; i++)
        {
            uint val = rng.Next();
            Console.WriteLine($"{i}: {val}");
        }

        // Test random(N) via Prng wrapper
        var prng = new Prng(PrngSeed.FromGen5(seed));
        Console.WriteLine("\n=== random(256) values (100) ===");
        for (var i = 0; i < 100; i++)
        {
            int val = prng.Random(256);
            Console.WriteLine($"{i}: {val}");
        }

        // Test random(min, max)
        var prng2 = new Prng(PrngSeed.FromGen5(seed));
        Console.WriteLine("\n=== random(10, 20) values (50) ===");
        for (var i = 0; i < 50; i++)
        {
            int val = prng2.Random(10, 20);
            Console.WriteLine($"{i}: {val}");
        }

        Console.WriteLine("Press Enter key to exit...");
        Console.ReadLine();
    }

    /// <summary>
    /// Run an equivalence test by replaying a Showdown fixture through the C# sim.
    /// The fixture is generated by: node Tools/EquivalenceTest/run_showdown_battle.js --random ...
    ///
    /// Compares protocol output line-by-line with Showdown's output.
    /// </summary>
    public void RunEquivalenceTest(string fixturePath, string showdownLogPath)
    {
        // Resolve paths relative to the solution root (walk up from bin output dir)
        // This handles both `dotnet run` (CWD = project root) and running the built exe
        if (!File.Exists(fixturePath))
        {
            string solutionRoot = EquivalenceTestHelper.FindSolutionRoot(AppContext.BaseDirectory);
            fixturePath = Path.Combine(solutionRoot, fixturePath);
            showdownLogPath = Path.Combine(solutionRoot, showdownLogPath);
        }

        Console.WriteLine($"[Equivalence] Loading fixture: {fixturePath}");
        Console.WriteLine($"[Equivalence] Loading Showdown log: {showdownLogPath}");

        string fixtureJson = File.ReadAllText(fixturePath);
        using JsonDocument doc = JsonDocument.Parse(fixtureJson);
        JsonElement root = doc.RootElement;

        // Parse seed
        string seedStr = root.GetProperty("seed").GetString()!;
        string[] seedParts = seedStr.Split(',');
        var gen5Seed = new Gen5RngSeed(
            ushort.Parse(seedParts[0]),
            ushort.Parse(seedParts[1]),
            ushort.Parse(seedParts[2]),
            ushort.Parse(seedParts[3]));

        // Parse format
        string formatId = root.GetProperty("formatid").GetString()!;
        FormatId fmtId = EquivalenceTestHelper.ResolveFormatId(formatId);

        // Parse teams
        var resolver = new ShowdownNameResolver(Library);
        var p1Team = EquivalenceTestHelper.ParseShowdownTeam(root.GetProperty("p1Team"), resolver, Library);
        var p2Team = EquivalenceTestHelper.ParseShowdownTeam(root.GetProperty("p2Team"), resolver, Library);

        Console.WriteLine($"[Equivalence] Format: {formatId}, Seed: {gen5Seed}");
        Console.WriteLine($"[Equivalence] P1 team: {string.Join(", ", p1Team.Select(p => p.Name))}");
        Console.WriteLine($"[Equivalence] P2 team: {string.Join(", ", p2Team.Select(p => p.Name))}");

        // Parse input log (choices)
        var inputLog = new List<string>();
        foreach (JsonElement entry in root.GetProperty("inputLog").EnumerateArray())
        {
            inputLog.Add(entry.GetString()!);
        }

        // Create battle with Gen5RNG seed
        var battleOptions = new BattleOptions
        {
            Id = fmtId,
            Sync = true,
            DisplayUi = true,
            Seed = PrngSeed.FromGen5(gen5Seed),
            Player1Options = new PlayerOptions
            {
                Name = "Player1",
                Team = p1Team.ToList(),
            },
            Player2Options = new PlayerOptions
            {
                Name = "Player2",
                Team = p2Team.ToList(),
            },
            MaxTurns = 1000,
        };

        var battle = new Battle(battleOptions, Library);
        battle.Prng.TraceEnabled = true;
        battle.Start();

        // Parse choice entries from input log (skip start/player setup lines)
        var choices = new Queue<string>();
        foreach (string logEntry in inputLog)
        {
            if (!logEntry.StartsWith(">")) continue;
            string line = logEntry[1..];
            if (line.StartsWith("start") || line.StartsWith("player")) continue;
            choices.Enqueue(line);
        }

        // Replay choices using the same loop pattern as SimulatorSync:
        // Battle.Start() sets up the first request, then we feed choices
        // and call CommitChoices(), which runs TurnLoop and may generate
        // new requests (forced switches after fainting, etc.)
        var choicesApplied = 0;
        while (!battle.Ended && battle.RequestState != RequestState.None)
        {
            // Feed choices for both sides from the input log
            // Feed choices from the queue, handling the case where one side
            // is already done (e.g. no forced switch needed)
            var madeProgress = true;
            while (choices.Count > 0 && !battle.AllChoicesDone() && madeProgress)
            {
                madeProgress = false;
                // Scan through queued choices to find ones we can apply
                var scanned = 0;
                int total = choices.Count;
                while (scanned < total && !battle.AllChoicesDone())
                {
                    string line = choices.Dequeue();
                    scanned++;

                    Side? side = null;
                    var choice = "";
                    if (line.StartsWith("p1 "))
                    {
                        side = battle.P1;
                        choice = line[3..];
                    }
                    else if (line.StartsWith("p2 "))
                    {
                        side = battle.P2;
                        choice = line[3..];
                    }

                    if (side is not null && !side.IsChoiceDone())
                    {
                        bool ok = side.Choose(choice);
                        if (!ok)
                            Console.WriteLine($"  [T{battle.Turn}] {side.Id} choice rejected: {choice} (State={battle.RequestState})");
                        choicesApplied++;
                        madeProgress = true;
                    }
                    else if (side is not null && side.IsChoiceDone())
                    {
                        // Side is already done — re-enqueue for later
                        choices.Enqueue(line);
                    }
                    // else: skip unknown lines
                }
            }

            if (battle.AllChoicesDone())
            {
                battle.CommitChoices();
            }
            else
            {
                Console.WriteLine($"  [T{battle.Turn}] Stuck: not all choices done, {choices.Count} entries remain (State={battle.RequestState})");
                break;
            }
        }

        Console.WriteLine($"[Equivalence] Applied {choicesApplied} choices, battle ended at turn {battle.Turn}");
        Console.WriteLine($"[Equivalence] Winner: {(battle.Winner != null ? battle.Winner : "none/tie")}");
        Console.WriteLine($"[Equivalence] C# log: {battle.Log.Count} lines");

        // Load Showdown log for comparison
        string[] showdownLines = File.ReadAllLines(showdownLogPath);

        // Filter to game-state-affecting lines for comparison
        var csharpFiltered = EquivalenceTestHelper.FilterProtocolLines(battle.Log);
        var showdownFiltered = EquivalenceTestHelper.FilterProtocolLines(showdownLines);

        Console.WriteLine($"[Equivalence] Filtered: C# {csharpFiltered.Count} lines, Showdown {showdownFiltered.Count} lines");

        // Find first mismatch and dump context around it
        int firstMismatchIdx = -1;
        for (var d = 0; d < Math.Min(csharpFiltered.Count, showdownFiltered.Count); d++)
        {
            if (csharpFiltered[d] != showdownFiltered[d]) { firstMismatchIdx = d; break; }
        }
        if (firstMismatchIdx >= 0)
        {
            int start = Math.Max(0, firstMismatchIdx - 3);
            int end = Math.Min(Math.Min(csharpFiltered.Count, showdownFiltered.Count), firstMismatchIdx + 10);
            Console.WriteLine($"\n=== Context around first mismatch (line {firstMismatchIdx}) ===");
            for (int d = start; d < end; d++)
            {
                string marker = d == firstMismatchIdx ? ">>>" : "   ";
                Console.WriteLine($"  {marker} C# [{d}]: {csharpFiltered[d]}");
                Console.WriteLine($"  {marker} SD [{d}]: {showdownFiltered[d]}");
            }
        }
        else if (csharpFiltered.Count < showdownFiltered.Count)
        {
            // C# ended early — show the last few C# lines and what SD expects next
            Console.WriteLine($"\n=== C# ended early (has {csharpFiltered.Count} vs SD {showdownFiltered.Count}) ===");
            int start = Math.Max(0, csharpFiltered.Count - 5);
            Console.WriteLine("  Last C# lines:");
            for (int d = start; d < csharpFiltered.Count; d++)
                Console.WriteLine($"    [{d}]: {csharpFiltered[d]}");
            Console.WriteLine("  Next SD lines:");
            for (int d = csharpFiltered.Count; d < Math.Min(showdownFiltered.Count, csharpFiltered.Count + 10); d++)
                Console.WriteLine($"    [{d}]: {showdownFiltered[d]}");
        }

        // Compare
        var matches = 0;
        var mismatches = 0;
        int maxLines = Math.Max(csharpFiltered.Count, showdownFiltered.Count);

        for (var i = 0; i < maxLines; i++)
        {
            string csLine = i < csharpFiltered.Count ? csharpFiltered[i] : "(missing)";
            string sdLine = i < showdownFiltered.Count ? showdownFiltered[i] : "(missing)";

            if (csLine == sdLine)
            {
                matches++;
            }
            else
            {
                mismatches++;
                if (mismatches <= 20) // Show first 20 mismatches
                {
                    Console.WriteLine($"\n  MISMATCH at line {i}:");
                    Console.WriteLine($"    C#:  {csLine}");
                    Console.WriteLine($"    SD:  {sdLine}");
                }
            }
        }

        Console.WriteLine($"\n[Equivalence] Result: {matches} matches, {mismatches} mismatches out of {maxLines} lines");

        if (mismatches == 0)
            Console.WriteLine("[Equivalence] PASS — protocols are identical!");
        else
            Console.WriteLine("[Equivalence] FAIL — protocols diverge");

        //// press Enter to exit so we can review the output
        //Console.WriteLine("Press Enter key to exit...");
        //Console.ReadLine();
    }

    }
