using System.Text.Json;
using ApogeeVGC.LiveAssist;
using ApogeeVGC.Sim.Abilities;
using ApogeeVGC.Sim.BattleClasses;
using ApogeeVGC.Sim.FormatClasses;
using ApogeeVGC.Sim.Items;
using ApogeeVGC.Sim.Moves;
using ApogeeVGC.Sim.PokemonClasses;
using ApogeeVGC.Sim.SpeciesClasses;
using ApogeeVGC.Sim.Stats;
using ApogeeVGC.Sim.Utils;

namespace ApogeeVGC.Sim.Core;

public partial class Driver
{
    /// <summary>
    /// Verify that Gen5Rng produces identical output to Showdown's Gen5RNG.
    /// Run the JS counterpart (Tools/EquivalenceTest/gen5rng_test.js) and compare output.
    /// </summary>
    public static void RunGen5RngVerification()
    {
        Console.WriteLine("=== Gen5RNG Verification ===");
        Console.WriteLine("Compare output with: node Tools/EquivalenceTest/gen5rng_test.js\n");

        var seed = new Gen5RngSeed(1, 2, 3, 4);

        // Test raw next() values
        var rng = new Gen5Rng(seed);
        Console.WriteLine("=== Raw next() values (100) ===");
        for (int i = 0; i < 100; i++)
        {
            uint val = rng.Next();
            Console.WriteLine($"{i}: {val}");
        }

        // Test random(N) via Prng wrapper
        var prng = new Prng(PrngSeed.FromGen5(seed));
        Console.WriteLine("\n=== random(256) values (100) ===");
        for (int i = 0; i < 100; i++)
        {
            int val = prng.Random(256);
            Console.WriteLine($"{i}: {val}");
        }

        // Test random(min, max)
        var prng2 = new Prng(PrngSeed.FromGen5(seed));
        Console.WriteLine("\n=== random(10, 20) values (50) ===");
        for (int i = 0; i < 50; i++)
        {
            int val = prng2.Random(10, 20);
            Console.WriteLine($"{i}: {val}");
        }

        Console.WriteLine("Press Enter key to exit...");
        Console.ReadLine();
    }

    /// <summary>
    /// Run an equivalence test by replaying a Showdown fixture through the C# sim.
    /// The fixture is generated by: node Tools/EquivalenceTest/run_showdown_battle.js --random ...
    ///
    /// Compares protocol output line-by-line with Showdown's output.
    /// </summary>
    public void RunEquivalenceTest(string fixturePath, string showdownLogPath)
    {
        Console.WriteLine($"[Equivalence] Loading fixture: {fixturePath}");
        Console.WriteLine($"[Equivalence] Loading Showdown log: {showdownLogPath}");

        string fixtureJson = File.ReadAllText(fixturePath);
        using JsonDocument doc = JsonDocument.Parse(fixtureJson);
        JsonElement root = doc.RootElement;

        // Parse seed
        string seedStr = root.GetProperty("seed").GetString()!;
        string[] seedParts = seedStr.Split(',');
        var gen5Seed = new Gen5RngSeed(
            ushort.Parse(seedParts[0]),
            ushort.Parse(seedParts[1]),
            ushort.Parse(seedParts[2]),
            ushort.Parse(seedParts[3]));

        // Parse format
        string formatId = root.GetProperty("formatid").GetString()!;
        FormatId fmtId = ResolveFormatId(formatId);

        // Parse teams
        var resolver = new ShowdownNameResolver(Library);
        PokemonSet[] p1Team = ParseShowdownTeam(root.GetProperty("p1Team"), resolver);
        PokemonSet[] p2Team = ParseShowdownTeam(root.GetProperty("p2Team"), resolver);

        Console.WriteLine($"[Equivalence] Format: {formatId}, Seed: {gen5Seed}");
        Console.WriteLine($"[Equivalence] P1 team: {string.Join(", ", p1Team.Select(p => p.Name))}");
        Console.WriteLine($"[Equivalence] P2 team: {string.Join(", ", p2Team.Select(p => p.Name))}");

        // Parse input log (choices)
        var inputLog = new List<string>();
        foreach (JsonElement entry in root.GetProperty("inputLog").EnumerateArray())
        {
            inputLog.Add(entry.GetString()!);
        }

        // Create battle with Gen5RNG seed
        var battleOptions = new BattleOptions
        {
            Id = fmtId,
            Sync = true,
            DisplayUi = false,
            Seed = PrngSeed.FromGen5(gen5Seed),
            Player1Options = new PlayerOptions
            {
                Name = "Player1",
                Team = p1Team.ToList(),
            },
            Player2Options = new PlayerOptions
            {
                Name = "Player2",
                Team = p2Team.ToList(),
            },
            MaxTurns = 1000,
        };

        var battle = new Battle(battleOptions, Library);
        battle.Start();

        // Replay choices from input log
        int choicesApplied = 0;
        foreach (string logEntry in inputLog)
        {
            if (!logEntry.StartsWith(">")) continue;
            string line = logEntry[1..]; // strip leading >

            if (line.StartsWith("p1 "))
            {
                string choice = line[3..];
                battle.P1.Choose(choice);
                choicesApplied++;
            }
            else if (line.StartsWith("p2 "))
            {
                string choice = line[3..];
                battle.P2.Choose(choice);
                choicesApplied++;
            }

            // After both sides have chosen, commit
            if (battle.AllChoicesDone())
            {
                battle.CommitChoices();
            }
        }

        Console.WriteLine($"[Equivalence] Applied {choicesApplied} choices, battle ended at turn {battle.Turn}");
        Console.WriteLine($"[Equivalence] Winner: {(battle.Winner != null ? battle.Winner : "none/tie")}");
        Console.WriteLine($"[Equivalence] C# log: {battle.Log.Count} lines");

        // Load Showdown log for comparison
        string[] showdownLines = File.ReadAllLines(showdownLogPath);

        // Filter to game-state-affecting lines for comparison
        var csharpFiltered = FilterProtocolLines(battle.Log);
        var showdownFiltered = FilterProtocolLines(showdownLines);

        Console.WriteLine($"[Equivalence] Filtered: C# {csharpFiltered.Count} lines, Showdown {showdownFiltered.Count} lines");

        // Compare
        int matches = 0;
        int mismatches = 0;
        int maxLines = Math.Max(csharpFiltered.Count, showdownFiltered.Count);

        for (int i = 0; i < maxLines; i++)
        {
            string csLine = i < csharpFiltered.Count ? csharpFiltered[i] : "(missing)";
            string sdLine = i < showdownFiltered.Count ? showdownFiltered[i] : "(missing)";

            if (csLine == sdLine)
            {
                matches++;
            }
            else
            {
                mismatches++;
                if (mismatches <= 20) // Show first 20 mismatches
                {
                    Console.WriteLine($"\n  MISMATCH at line {i}:");
                    Console.WriteLine($"    C#:  {csLine}");
                    Console.WriteLine($"    SD:  {sdLine}");
                }
            }
        }

        Console.WriteLine($"\n[Equivalence] Result: {matches} matches, {mismatches} mismatches out of {maxLines} lines");

        if (mismatches == 0)
            Console.WriteLine("[Equivalence] PASS — protocols are identical!");
        else
            Console.WriteLine("[Equivalence] FAIL — protocols diverge");
    }

    /// <summary>
    /// Filter protocol lines to game-state-affecting entries only.
    /// Strips animation hints, empty lines, and channel markers.
    /// </summary>
    private static List<string> FilterProtocolLines(IEnumerable<string> lines)
    {
        var result = new List<string>();
        foreach (string line in lines)
        {
            if (string.IsNullOrWhiteSpace(line)) continue;

            // Skip channel/split markers and meta-protocol
            if (line.StartsWith("|split|")) continue;
            if (line.StartsWith("|upkeep")) continue;
            if (line == "|") continue;
            if (line.StartsWith("update")) continue;
            if (line.StartsWith("sideupdate")) continue;

            // Skip animation-only lines
            if (line.StartsWith("|-anim|")) continue;

            // Include game-state lines
            if (line.StartsWith("|") || line.StartsWith("|-"))
            {
                result.Add(line);
            }
        }
        return result;
    }

    /// <summary>
    /// Parse a Showdown JSON team array into C# PokemonSet[].
    /// Expects the unpacked team format from Teams.unpack() (species, moves, ability, item, etc.).
    /// </summary>
    private PokemonSet[] ParseShowdownTeam(JsonElement teamArray, ShowdownNameResolver resolver)
    {
        var sets = new List<PokemonSet>();
        foreach (JsonElement mon in teamArray.EnumerateArray())
        {
            string species = mon.GetProperty("species").GetString()!;
            SpecieId specieId = resolver.ResolveSpecies(species);
            if (specieId == default)
            {
                Console.WriteLine($"  WARNING: Unknown species '{species}', skipping");
                continue;
            }

            // Moves
            var moves = new List<MoveId>();
            foreach (JsonElement m in mon.GetProperty("moves").EnumerateArray())
            {
                string moveName = m.GetString()!;
                MoveId moveId = resolver.ResolveMove(moveName);
                if (moveId != MoveId.None)
                    moves.Add(moveId);
                else
                    Console.WriteLine($"  WARNING: Unknown move '{moveName}' on {species}");
            }
            if (moves.Count == 0) moves.Add(MoveId.Tackle);

            // Ability
            string abilityName = mon.GetProperty("ability").GetString() ?? "";
            AbilityId abilityId = resolver.ResolveAbility(abilityName);

            // Item
            string itemName = mon.GetProperty("item").GetString() ?? "";
            ItemId itemId = resolver.ResolveItem(itemName);

            // Nature
            string natureName = mon.TryGetProperty("nature", out JsonElement natElem)
                ? natElem.GetString() ?? "Serious" : "Serious";
            NatureId natureId = Enum.TryParse<NatureId>(natureName, true, out var nid) ? nid : NatureId.Serious;
            Nature nature = Library.Natures[natureId];

            // EVs
            var evs = new StatsTable();
            if (mon.TryGetProperty("evs", out JsonElement evsElem))
            {
                evs = new StatsTable
                {
                    Hp = evsElem.TryGetProperty("hp", out var hp) ? hp.GetInt32() : 0,
                    Atk = evsElem.TryGetProperty("atk", out var atk) ? atk.GetInt32() : 0,
                    Def = evsElem.TryGetProperty("def", out var def) ? def.GetInt32() : 0,
                    SpA = evsElem.TryGetProperty("spa", out var spa) ? spa.GetInt32() : 0,
                    SpD = evsElem.TryGetProperty("spd", out var spd) ? spd.GetInt32() : 0,
                    Spe = evsElem.TryGetProperty("spe", out var spe) ? spe.GetInt32() : 0,
                };
            }

            // IVs
            var ivs = StatsTable.PerfectIvs;
            if (mon.TryGetProperty("ivs", out JsonElement ivsElem))
            {
                ivs = new StatsTable
                {
                    Hp = ivsElem.TryGetProperty("hp", out var hp) ? hp.GetInt32() : 31,
                    Atk = ivsElem.TryGetProperty("atk", out var atk) ? atk.GetInt32() : 31,
                    Def = ivsElem.TryGetProperty("def", out var def) ? def.GetInt32() : 31,
                    SpA = ivsElem.TryGetProperty("spa", out var spa) ? spa.GetInt32() : 31,
                    SpD = ivsElem.TryGetProperty("spd", out var spd) ? spd.GetInt32() : 31,
                    Spe = ivsElem.TryGetProperty("spe", out var spe) ? spe.GetInt32() : 31,
                };
            }

            // Level
            int level = mon.TryGetProperty("level", out JsonElement lvl) ? lvl.GetInt32() : 50;

            // Tera type
            MoveType teraType = default;
            if (mon.TryGetProperty("teraType", out JsonElement tera))
            {
                string teraStr = tera.GetString() ?? "";
                teraType = resolver.ResolveTeraType(teraStr);
            }

            // Gender
            GenderId gender = GenderId.N;
            if (mon.TryGetProperty("gender", out JsonElement genderElem))
            {
                string g = genderElem.GetString() ?? "";
                gender = g switch
                {
                    "M" => GenderId.M,
                    "F" => GenderId.F,
                    _ => GenderId.N,
                };
            }

            sets.Add(new PokemonSet
            {
                Name = mon.TryGetProperty("name", out JsonElement nameElem)
                    ? nameElem.GetString() ?? species : species,
                Species = specieId,
                Item = itemId,
                Ability = abilityId,
                Moves = moves,
                Nature = nature,
                Evs = evs,
                Ivs = ivs,
                Level = level,
                TeraType = teraType,
                Gender = gender,
            });
        }

        return sets.ToArray();
    }

    private static FormatId ResolveFormatId(string formatId) => formatId switch
    {
        "gen9vgc2024regg" => FormatId.Gen9VgcRegulationG,
        "gen9vgc2024regh" => FormatId.Gen9VgcRegulationH,
        "gen9vgc2024regi" or "gen9vgc2025regi" => FormatId.Gen9VgcRegulationI,
        "gen9vgcmega" => FormatId.Gen9VgcMega,
        _ => throw new ArgumentException($"Unknown format: {formatId}"),
    };
}
