namespace ApogeeVGC.Sim.Moves;

public enum MoveId
{
    GlacialLance,
    LeechSeed,
    TrickRoom,
    Protect,
    VoltSwitch,
    DazzlingGleam,
    ElectroDrift,
    DracoMeteor,
Facade,
  Crunch,
    HeadlongRush,
    StruggleBug,
    Overheat,
    //RagePowder,
    Tailwind,
    SpiritBreak,
    ThunderWave,
    Reflect,
    LightScreen,
    FakeOut,
  HeavySlam,
 LowKick,
    WildCharge,
 MeFirst,
    BurnUp,
    PolarFlare,
    AxeKick,
    Snatch,
    Yawn,
    BellyDrum,
    Recycle,
    Trick,
    Switcheroo,
    Recharge,
    Frustration,
    Return,
    Curse,
    PollenPuff,
    TeraStarStorm,
    BehemothBlade,
    BehemothBash,
    IronHead,
    RevivalBlessing,
    SolarBeam,
    SolarBlade,
    ElectroShot,
    SkyDrop,
    Instruct,
    Toxic,
 HelpingHand,
    Feint,
    Chloroblast,
    SpectralThief,

    Struggle,
  Confused, // The move pokemon use to hit themselves in confusion

    None,

  //// Custom moves
    //NormalBasic,
    //FireBasic,
    //WaterBasic,
  //ElectricBasic,
    //GrassBasic,
    //IceBasic,
    //FightingBasic,
    //PoisonBasic,
    //GroundBasic,
    //FlyingBasic,
    //PsychicBasic,
    //BugBasic,
    //RockBasic,
    //GhostBasic,
    //DragonBasic,
    //DarkBasic,
    //SteelBasic,
    //FairyBasic,
}
