#pragma once

#include "event_methods_aliases.h"

struct EventMethods
{
	OnDamagingHitFunc* on_damaging_hit = nullptr;
	OnEmergencyExitFunc* on_emergency_exit = nullptr;
	OnAfterEachBoostFunc* on_after_each_boost = nullptr;
	OnAfterHitFunc* on_after_hit = nullptr;
	OnAfterMegaFunc* on_after_mega = nullptr;
	OnAfterSetStatusFunc* on_after_set_status = nullptr;
	OnAfterSubDamageFunc* on_after_sub_damage = nullptr;
	OnAfterSwitchInSelfFunc* on_after_switch_in_self = nullptr;
	OnAfterTerastallizationFunc* on_after_terastallization = nullptr;
	OnAfterUseItemFunc* on_after_use_item = nullptr;
	OnAfterTakeItemFunc* on_after_take_item = nullptr;
	OnAfterBoostFunc* on_after_boost = nullptr;
	OnAfterFaintFunc* on_after_faint = nullptr;
	OnAfterMoveSecondarySelfFunc* on_after_move_secondary_self = nullptr;
	OnAfterMoveSecondaryFunc* on_after_move_secondary = nullptr;
	OnAfterMoveFunc* on_after_move = nullptr;
	VoidSourceMoveFunc* on_after_move_self = nullptr; // from CommonHandlers
	OnAttractFunc* on_attract = nullptr;
	OnAccuracyFunc* on_accuracy = nullptr;
	ModifierSourceMoveFunc* on_base_power = nullptr; // from CommonHandlers
	OnBeforeFaintFunc* on_before_faint = nullptr;
	VoidSourceMoveFunc* on_before_move = nullptr; // from CommonHandlers
	OnBeforeSwitchInFunc* on_before_switch_in = nullptr;
	OnBeforeSwitchOutFunc* on_before_switch_out = nullptr;
	OnBeforeTurnFunc* on_before_turn = nullptr;
	OnChangeBoostFunc* on_change_boost = nullptr;
	OnTryBoostFunc* on_try_boost = nullptr;
	VoidSourceMoveFunc* on_charge_move = nullptr; // from CommonHandlers
	OnCriticalHitFunc* on_critical_hit = nullptr; // from CommonHandlers
	OnDamageFunc* on_damage = nullptr; // from CommonHandlers

	OnDeductPPFunc* on_deduct_pp = nullptr;
	OnDisableMoveFunc* on_disable_move = nullptr;
	OnDragOutFunc* on_drag_out = nullptr; // from CommonHandlers
	OnEatItemFunc* on_eat_item = nullptr;
	OnEffectivenessFunc* on_effectiveness = nullptr; // from MoveEventMethods
	OnEntryHazardFunc* on_entry_hazard = nullptr; // from CommonHandlers
	VoidEffectFunc* on_faint = nullptr; // from CommonHandlers
	OnFlinchFunc* on_flinch = nullptr; // from CommonHandlers
	OnFractionalPriorityFunc* on_fractional_priority = nullptr; // from CommonHandlers
	OnHitFunc* on_hit = nullptr; // from MoveEventMethods
	OnImmunityFunc* on_immunity = nullptr;
	OnLockMoveFunc* on_lock_move = nullptr; // from CommonHandlers
	OnMaybeTrapPokemonFunc* on_maybe_trap_pokemon = nullptr; // from CommonHandlers
	ModifierMoveFunc* on_modify_accuracy = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_modify_atk = nullptr; // from CommonHandlers
	OnModifyBoostFunc* on_modify_boost = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_modify_crit_ratio = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_modify_damage = nullptr; // from CommonHandlers
	ModifierMoveFunc* on_modify_def = nullptr; // from CommonHandlers
	OnModifyMoveFunc* on_modify_move = nullptr; // from MoveEventMethods
	ModifierSourceMoveFunc* on_modify_priority = nullptr; // from CommonHandlers
	OnModifySecondariesFunc* on_modify_secondaries = nullptr; // from CommonHandlers
	OnModifyTypeFunc* on_modify_type = nullptr; // from MoveEventMethods
	OnModifyTargetFunc* on_modify_target = nullptr; // from MoveEventMethods
	ModifierSourceMoveFunc* on_modify_spa = nullptr; // from CommonHandlers
	ModifierMoveFunc* on_modify_spd = nullptr; // from CommonHandlers
	OnModifySpeFunc* on_modify_spe = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_modify_stab = nullptr; // from CommonHandlers
	OnModifyWeightFunc* on_modify_weight = nullptr; // from CommonHandlers
	VoidMoveFunc* on_move_aborted = nullptr; // from CommonHandlers
	OnNegateImmunityFunc* on_negate_immunity = nullptr; // from CommonHandlers
	OnOverrideActionFunc* on_override_action = nullptr; // from CommonHandlers
	ResultSourceMoveFunc* on_prepare_hit = nullptr; // from CommonHandlers
	OnPseudoWeatherChangeFunc* on_pseudo_weather_change = nullptr; // from CommonHandlers
	OnRedirectTargetFunc* on_redirect_target = nullptr; // from CommonHandlers
	OnResidualFunc* on_residual = nullptr; // from CommonHandlers
	OnSetAbilityFunc* on_set_ability = nullptr; // from CommonHandlers
	OnSetStatusFunc* on_set_status = nullptr; // from CommonHandlers

	OnSetWeatherFunc* on_set_weather = nullptr; // from CommonHandlers
	OnSideConditionStartFunc* on_side_condition_start = nullptr; // from CommonHandlers
	OnStallMoveFunc* on_stall_move = nullptr; // from CommonHandlers
	OnSwitchInFunc* on_switch_in = nullptr; // from CommonHandlers
	OnSwitchOutFunc* on_switch_out = nullptr; // from CommonHandlers
	OnSwapFunc* on_swap = nullptr; // from CommonHandlers
	OnTakeItemFunc* on_take_item = nullptr; // from CommonHandlers
	OnWeatherChangeFunc* on_weather_change = nullptr; // from CommonHandlers
	OnTerrainChangeFunc* on_terrain_change = nullptr; // from CommonHandlers
	OnTrapPokemonFunc* on_trap_pokemon = nullptr; // from CommonHandlers
	OnTryAddVolatileFunc* on_try_add_volatile = nullptr; // from CommonHandlers
	OnTryEatItemFunc* on_try_eat_item = nullptr; // from CommonHandlers
	OnTryHealFunc* on_try_heal = nullptr; // from CommonHandlers
	OnTryPrimaryHitFunc* on_try_primary_hit = nullptr; // from CommonHandlers
	OnTypeFunc* on_type = nullptr; // from CommonHandlers
	OnUseItemFunc* on_use_item = nullptr; // from CommonHandlers
	OnUpdateFunc* on_update = nullptr; // from CommonHandlers
	OnWeatherFunc* on_weather = nullptr; // from CommonHandlers

	ModifierSourceMoveFunc* on_weather_modify_damage = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_modify_damage_phase_1 = nullptr; // from CommonHandlers
	OnModifyDamagePhase2Func* on_modify_damage_phase_2 = nullptr; // from CommonHandlers
	OnFoeDamagingHitFunc* on_foe_damaging_hit = nullptr; // from CommonHandlers
	OnFoeAfterEachBoostFunc* on_foe_after_each_boost = nullptr; // from CommonHandlers
	OnAfterHitFunc* on_foe_after_hit = nullptr; // from MoveEventMethods
	OnFoeAfterSetStatusFunc* on_foe_after_set_status = nullptr; // from CommonHandlers
	OnAfterSubDamageFunc* on_foe_after_sub_damage = nullptr; // from MoveEventMethods
	OnFoeAfterSwitchInSelfFunc* on_foe_after_switch_in_self = nullptr; // from CommonHandlers
	OnFoeAfterUseItemFunc* on_foe_after_use_item = nullptr; // from CommonHandlers
	OnFoeAfterBoostFunc* on_foe_after_boost = nullptr; // from CommonHandlers
	OnFoeAfterFaintFunc* on_foe_after_faint = nullptr; // from CommonHandlers
	OnAfterMoveSecondarySelfFunc* on_foe_after_move_secondary_self = nullptr; // from MoveEventMethods
	OnAfterMoveSecondaryFunc* on_foe_after_move_secondary = nullptr; // from MoveEventMethods
	OnAfterMoveFunc* on_foe_after_move = nullptr; // from MoveEventMethods
	VoidSourceMoveFunc* on_foe_after_move_self = nullptr; // from CommonHandlers
	OnFoeAttractFunc* on_foe_attract = nullptr; // from CommonHandlers
	OnFoeAccuracyFunc* on_foe_accuracy = nullptr; // from CommonHandlers

	ModifierSourceMoveFunc* on_foe_base_power = nullptr; // from CommonHandlers
	OnFoeBeforeFaintFunc* on_foe_before_faint = nullptr; // from CommonHandlers
	VoidSourceMoveFunc* on_foe_before_move = nullptr; // from CommonHandlers
	OnFoeBeforeSwitchInFunc* on_foe_before_switch_in = nullptr; // from CommonHandlers
	OnFoeBeforeSwitchOutFunc* on_foe_before_switch_out = nullptr; // from CommonHandlers
	OnFoeTryBoostFunc* on_foe_try_boost = nullptr; // from CommonHandlers
	VoidSourceMoveFunc* on_foe_charge_move = nullptr; // from CommonHandlers
	OnFoeCriticalHitFunc* on_foe_critical_hit = nullptr; // from CommonHandlers
	OnFoeDamageFunc* on_foe_damage = nullptr; // from CommonHandlers
	OnFoeDeductPPFunc* on_foe_deduct_pp = nullptr; // from CommonHandlers
	OnFoeDisableMoveFunc* on_foe_disable_move = nullptr; // from CommonHandlers
	OnFoeDragOutFunc* on_foe_drag_out = nullptr; // from CommonHandlers
	OnFoeEatItemFunc* on_foe_eat_item = nullptr; // from CommonHandlers
	OnEffectivenessFunc* on_foe_effectiveness = nullptr;  // from MoveEventMethods
	OnFoeFaintFunc* on_foe_faint = nullptr; // from CommonHandlers
	OnFoeFlinchFunc* on_foe_flinch = nullptr; // from CommonHandlers
	OnHitFunc* on_foe_hit = nullptr; // from MoveEventMethods
	OnFoeImmunityFunc* on_foe_immunity = nullptr; // from CommonHandlers
	OnFoeLockMoveFunc* on_foe_lock_move = nullptr; // from CommonHandlers
	OnFoeMaybeTrapPokemonFunc* on_foe_maybe_trap_pokemon = nullptr; // from CommonHandlers
	ModifierMoveFunc* on_foe_modify_accuracy = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_foe_modify_atk = nullptr; // from CommonHandlers
	OnFoeModifyBoostFunc* on_foe_modify_boost = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_foe_modify_crit_ratio = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_foe_modify_damage = nullptr; // from CommonHandlers
	ModifierMoveFunc* on_foe_modify_def = nullptr; // from CommonHandlers
	OnModifyMoveFunc* on_foe_modify_move = nullptr; // from MoveEventMethods
	ModifierSourceMoveFunc* on_foe_modify_priority = nullptr; // from CommonHandlers
	OnFoeModifySecondariesFunc* on_foe_modify_secondaries = nullptr; // from CommonHandlers

	ModifierSourceMoveFunc* on_foe_modify_spa = nullptr; // from CommonHandlers
	ModifierMoveFunc* on_foe_modify_spd = nullptr; // from CommonHandlers
	OnFoeModifySpeFunc* on_foe_modify_spe = nullptr;
	ModifierSourceMoveFunc* on_foe_modify_stab = nullptr; // from CommonHandlers
	OnModifyTypeFunc* on_foe_modify_type = nullptr; // from MoveEventMethods
	OnModifyTargetFunc* on_foe_modify_target = nullptr; // from MoveEventMethods
	OnFoeModifyWeightFunc* on_foe_modify_weight = nullptr;
	VoidMoveFunc* on_foe_move_aborted = nullptr; // from CommonHandlers
	OnFoeNegateImmunityFunc* on_foe_negate_immunity = nullptr;
	OnFoeOverrideActionFunc* on_foe_override_action = nullptr;
	ResultSourceMoveFunc* on_foe_prepare_hit = nullptr; // from CommonHandlers
	OnFoeRedirectTargetFunc* on_foe_redirect_target = nullptr;
	OnFoeResidualFunc* on_foe_residual = nullptr;
	OnFoeSetAbilityFunc* on_foe_set_ability = nullptr;
	OnFoeSetStatusFunc* on_foe_set_status = nullptr;
	OnFoeSetWeatherFunc* on_foe_set_weather = nullptr;
	OnFoeSideConditionStartFunc* on_foe_side_condition_start = nullptr;
	OnFoeStallMoveFunc* on_foe_stall_move = nullptr;
	OnFoeSwitchOutFunc* on_foe_switch_out = nullptr;
	OnFoeSwapFunc* on_foe_swap = nullptr;
	OnFoeTakeItemFunc* on_foe_take_item = nullptr;
	OnFoeWeatherChangeFunc* on_foe_weather_change = nullptr;
	OnFoeTerrainChangeFunc* on_foe_terrain_change = nullptr;
	OnFoeTrapPokemonFunc* on_foe_trap_pokemon = nullptr;
	OnFoeTryAddVolatileFunc* on_foe_try_add_volatile = nullptr;
	OnFoeTryEatItemFunc* on_foe_try_eat_item = nullptr;
	OnFoeTryHealFunc* on_foe_try_heal = nullptr;

	OnTryHitFunc* on_foe_try_hit = nullptr; // from MoveEventMethods
	OnTryHitFieldFunc* on_foe_try_hit_field = nullptr; // from MoveEventMethods
	ResultMoveFunc* on_foe_try_hit_side = nullptr; // from CommonHandlers
	ExtResultMoveFunc* on_foe_invulnerability = nullptr; // from CommonHandlers
	OnTryMoveFunc* on_foe_try_move = nullptr; // from MoveEventMethods
	OnFoeTryPrimaryHitFunc* on_foe_try_primary_hit = nullptr;
	OnFoeTypeFunc* on_foe_type = nullptr;
	ModifierSourceMoveFunc* on_foe_weather_modify_damage = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_foe_modify_damage_phase_1 = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_foe_modify_damage_phase_2 = nullptr; // from CommonHandlers
	OnSourceDamagingHitFunc* on_source_damaging_hit = nullptr;
	OnSourceAfterEachBoostFunc* on_source_after_each_boost = nullptr;
	OnAfterHitFunc* on_source_after_hit = nullptr; // from MoveEventMethods
	OnSourceAfterSetStatusFunc* on_source_after_set_status = nullptr;
	OnAfterSubDamageFunc* on_source_after_sub_damage = nullptr; // from MoveEventMethods
	OnSourceAfterSwitchInSelfFunc* on_source_after_switch_in_self = nullptr;
	OnSourceAfterUseItemFunc* on_source_after_use_item = nullptr;
	OnSourceAfterBoostFunc* on_source_after_boost = nullptr;
	OnSourceAfterFaintFunc* on_source_after_faint = nullptr;
	OnAfterMoveSecondarySelfFunc* on_source_after_move_secondary_self = nullptr; // from MoveEventMethods
	OnAfterMoveSecondaryFunc* on_source_after_move_secondary = nullptr; // from MoveEventMethods
	OnAfterMoveFunc* on_source_after_move = nullptr; // from MoveEventMethods
	VoidSourceMoveFunc* on_source_after_move_self = nullptr;
	OnSourceAttractFunc* on_source_attract = nullptr;
	OnSourceAccuracyFunc* on_source_accuracy = nullptr;

	ModifierSourceMoveFunc* on_source_base_power = nullptr; // from CommonHandlers
	OnSourceBeforeFaintFunc* on_source_before_faint = nullptr;
	VoidSourceMoveFunc* on_source_before_move = nullptr;
	OnSourceBeforeSwitchInFunc* on_source_before_switch_in = nullptr;
	OnSourceBeforeSwitchOutFunc* on_source_before_switch_out = nullptr;
	OnSourceTryBoostFunc* on_source_try_boost = nullptr;
	VoidSourceMoveFunc* on_source_charge_move = nullptr; // from CommonHandlers
	OnSourceCriticalHitFunc* on_source_critical_hit = nullptr;
	OnSourceDamageFunc* on_source_damage = nullptr;
	OnSourceDeductPPFunc* on_source_deduct_pp = nullptr;
	OnSourceDisableMoveFunc* on_source_disable_move = nullptr;
	OnSourceDragOutFunc* on_source_drag_out = nullptr;
	OnSourceEatItemFunc* on_source_eat_item = nullptr;
	OnEffectivenessFunc* on_source_effectiveness = nullptr; // from MoveEventMethods
	VoidEffectFunc* on_source_faint = nullptr; // from CommonHandlers

	OnSourceFlinchFunc* on_source_flinch = nullptr;
	OnHitFunc* on_source_hit = nullptr; // from MoveEventMethods
	OnSourceImmunityFunc* on_source_immunity = nullptr;
	OnSourceLockMoveFunc* on_source_lock_move = nullptr;
	OnSourceMaybeTrapPokemonFunc* on_source_maybe_trap_pokemon = nullptr;
	ModifierMoveFunc* on_source_modify_accuracy = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_source_modify_atk = nullptr; // from CommonHandlers
	OnSourceModifyBoostFunc* on_source_modify_boost = nullptr;
	ModifierSourceMoveFunc* on_source_modify_crit_ratio = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_source_modify_damage = nullptr; // from CommonHandlers
	ModifierMoveFunc* on_source_modify_def = nullptr; // from CommonHandlers
	OnModifyMoveFunc* on_source_modify_move = nullptr; // from MoveEventMethods
	ModifierSourceMoveFunc* on_source_modify_priority = nullptr; // from CommonHandlers
	OnSourceModifySecondariesFunc* on_source_modify_secondaries = nullptr;

	ModifierSourceMoveFunc* on_source_modify_spa = nullptr; // from CommonHandlers
	ModifierMoveFunc* on_source_modify_spd = nullptr; // from CommonHandlers
	OnSourceModifySpeFunc* on_source_modify_spe = nullptr;
	ModifierSourceMoveFunc* on_source_modify_stab = nullptr; // from CommonHandlers
	OnModifyTypeFunc* on_source_modify_type = nullptr; // from MoveEventMethods
	OnModifyTargetFunc* on_source_modify_target = nullptr; // from MoveEventMethods
	OnSourceModifyWeightFunc* on_source_modify_weight = nullptr;
	VoidMoveFunc* on_source_move_aborted = nullptr; // from CommonHandlers
	OnSourceNegateImmunityFunc* on_source_negate_immunity = nullptr;
	OnSourceOverrideActionFunc* on_source_override_action = nullptr;
	ResultSourceMoveFunc* on_source_prepare_hit = nullptr; // from CommonHandlers
	OnSourceRedirectTargetFunc* on_source_redirect_target = nullptr;
	OnSourceResidualFunc* on_source_residual = nullptr;
	OnSourceSetAbilityFunc* on_source_set_ability = nullptr;
	OnSourceSetStatusFunc* on_source_set_status = nullptr;

	OnSourceSetWeatherFunc* on_source_set_weather = nullptr;
	OnSourceStallMoveFunc* on_source_stall_move = nullptr;
	OnSourceSwitchOutFunc* on_source_switch_out = nullptr;
	OnSourceTakeItemFunc* on_source_take_item = nullptr;
	OnSourceTerrainFunc* on_source_terrain_change = nullptr;
	OnSourceTrapPokemonFunc* on_source_trap_pokemon = nullptr;
	OnSourceTryAddVolatileFunc* on_source_try_add_volatile = nullptr;
	OnSourceTryEatItemFunc* on_source_try_eat_item = nullptr;
	OnSourceTryHealFunc* on_source_try_heal = nullptr;
	OnTryHitFunc* on_source_try_hit = nullptr; // from MoveEventMethods
	OnTryHitFieldFunc* on_source_try_hit_field = nullptr; // from MoveEventMethods
	ResultMoveFunc* on_source_try_hit_side = nullptr; // from CommonHandlers
	ExtResultMoveFunc* on_source_invulnerability = nullptr; // from CommonHandlers
	OnTryMoveFunc* on_source_try_move = nullptr; // from MoveEventMethods
	OnSourceTryPrimaryHitFunc* on_source_try_primary_hit = nullptr;

	OnSourceTypeFunc* on_source_type = nullptr;
	ModifierSourceMoveFunc* on_source_weather_modify_damage = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_source_modify_damage_phase_1 = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_source_modify_damage_phase_2 = nullptr; // from CommonHandlers
	OnAnyDamagingHitFunc* on_any_damaging_hit = nullptr;
	OnAnyAfterEachBoostFunc* on_any_after_each_boost = nullptr;
	OnAfterHitFunc* on_any_after_hit = nullptr; // from MoveEventMethods
	OnAnyAfterSetStatusFunc* on_any_after_set_status = nullptr;
	OnAfterSubDamageFunc* on_any_after_sub_damage = nullptr; // from MoveEventMethods
	OnAnyAfterSwitchInSelfFunc* on_any_after_switch_in_self = nullptr;
	OnAnyAfterUseItemFunc* on_any_after_use_item = nullptr;
	OnAnyAfterBoostFunc* on_any_after_boost = nullptr;
	OnAnyAfterFaintFunc* on_any_after_faint = nullptr;
	OnAnyAfterMegaFunc* on_any_after_mega = nullptr;

	OnAfterMoveSecondarySelfFunc* on_any_after_move_secondary_self = nullptr; // from MoveEventMethods
	OnAfterMoveSecondaryFunc* on_any_after_move_secondary = nullptr; // from MoveEventMethods
	OnAfterMoveFunc* on_any_after_move = nullptr; // from MoveEventMethods
	VoidSourceMoveFunc* on_any_after_move_self = nullptr;
	OnAnyAttractFunc* on_any_attract = nullptr;
	OnAnyAccuracyFunc* on_any_accuracy = nullptr;
	ModifierSourceMoveFunc* on_any_base_power = nullptr; // from CommonHandlers
	OnAnyBeforeFaintFunc* on_any_before_faint = nullptr;
	VoidSourceMoveFunc* on_any_before_move = nullptr;
	OnAnyBeforeSwitchInFunc* on_any_before_switch_in = nullptr;
	OnAnyBeforeSwitchOutFunc* on_any_before_switch_out = nullptr;
	OnAnyTryBoostFunc* on_any_try_boost = nullptr;
	VoidSourceMoveFunc* on_any_charge_move = nullptr;
	OnAnyCriticalHitFunc* on_any_critical_hit = nullptr;

	OnAnyDamageFunc* on_any_damage = nullptr;
	OnAnyDeductPPFunc* on_any_deduct_pp = nullptr;
	OnAnyDisableMoveFunc* on_any_disable_move = nullptr;
	OnAnyDragOutFunc* on_any_drag_out = nullptr;
	OnAnyEatItemFunc* on_any_eat_item = nullptr;
	OnEffectivenessFunc* on_any_effectiveness = nullptr; // from MoveEventMethods
	VoidEffectFunc* on_any_faint = nullptr; // from CommonHandlers
	OnAnyFlinchFunc* on_any_flinch = nullptr;
	OnHitFunc* on_any_hit = nullptr; // from MoveEventMethods
	OnAnyImmunityFunc* on_any_immunity = nullptr;
	OnAnyLockMoveFunc* on_any_lock_move = nullptr;
	OnAnyMaybeTrapPokemonFunc* on_any_maybe_trap_pokemon = nullptr;
	ModifierMoveFunc* on_any_modify_accuracy = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_any_modify_atk = nullptr; // from CommonHandlers

	OnAnyModifyBoostFunc* on_any_modify_boost = nullptr;
	ModifierSourceMoveFunc* on_any_modify_crit_ratio = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_any_modify_damage = nullptr; // from CommonHandlers
	ModifierMoveFunc* on_any_modify_def = nullptr; // from CommonHandlers
	OnModifyMoveFunc* on_any_modify_move = nullptr; // from MoveEventMethods
	ModifierSourceMoveFunc* on_any_modify_priority = nullptr; // from CommonHandlers
	OnAnyModifySecondariesFunc* on_any_modify_secondaries = nullptr;
	ModifierSourceMoveFunc* on_any_modify_spa = nullptr; // from CommonHandlers
	ModifierMoveFunc* on_any_modify_spd = nullptr; // from CommonHandlers
	OnAnyModifySpeFunc* on_any_modify_spe = nullptr;
	ModifierSourceMoveFunc* on_any_modify_stab = nullptr; // from CommonHandlers
	OnModifyTypeFunc* on_any_modify_type = nullptr; // from MoveEventMethods
	OnModifyTargetFunc* on_any_modify_target = nullptr; // from MoveEventMethods
	OnAnyModifyWeightFunc* on_any_modify_weight = nullptr;
	VoidMoveFunc* on_any_move_aborted = nullptr;

	OnAnyNegateImmunityFunc* on_any_negate_immunity = nullptr;
	OnAnyOverrideActionFunc* on_any_override_action = nullptr;
	ResultSourceMoveFunc* on_any_prepare_hit = nullptr;
	OnAnyRedirectTargetFunc* on_any_redirect_target = nullptr;
	OnAnyResidualFunc* on_any_residual = nullptr;
	OnAnySetAbilityFunc* on_any_set_ability = nullptr;
	OnAnySetStatusFunc* on_any_set_status = nullptr;
	OnAnySetWeatherFunc* on_any_set_weather = nullptr;
	OnAnyStallMoveFunc* on_any_stall_move = nullptr;
	OnAnySwitchInFunc* on_any_switch_in = nullptr;
	OnAnySwitchOutFunc* on_any_switch_out = nullptr;
	OnAnyTakeItemFunc* on_any_take_item = nullptr;

	OnAnyTerrainFunc* on_any_terrain_change = nullptr;
	OnAnyTrapPokemonFunc* on_any_trap_pokemon = nullptr;
	OnAnyTryAddVolatileFunc* on_any_try_add_volatile = nullptr;
	OnAnyTryEatItemFunc* on_any_try_eat_item = nullptr;
	OnAnyTryHealFunc* on_any_try_heal = nullptr;
	OnTryHitFunc* on_any_try_hit = nullptr; // from MoveEventMethods
	OnTryHitFieldFunc* on_any_try_hit_field = nullptr; // from MoveEventMethods
	ResultMoveFunc* on_any_try_hit_side = nullptr; // from CommonHandlers
	ExtResultMoveFunc* on_any_invulnerability = nullptr; // from CommonHandlers
	OnTryMoveFunc* on_any_try_move = nullptr; // from MoveEventMethods
	OnAnyTryPrimaryHitFunc* on_any_try_primary_hit = nullptr;
	OnAnyTypeFunc* on_any_type = nullptr;
	ModifierSourceMoveFunc* on_any_weather_modify_damage = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_any_modify_damage_phase_1 = nullptr; // from CommonHandlers
	ModifierSourceMoveFunc* on_any_modify_damage_phase_2 = nullptr; // from CommonHandlers

	int* on_accuracy_priority = nullptr;
	int* on_damaging_hit_order = nullptr;
	int* on_after_move_secondary_priority = nullptr;
	int* on_after_move_secondary_self_priority = nullptr;
	int* on_after_move_self_priority = nullptr;
	int* on_after_set_status_priority = nullptr;
	int* on_any_base_power_priority = nullptr;
	int* on_any_invulnerability_priority = nullptr;
	int* on_any_modify_accuracy_priority = nullptr;
	int* on_any_faint_priority = nullptr;
	int* on_any_prepare_hit_priority = nullptr;
	int* on_any_switch_in_priority = nullptr;
	int* on_any_switch_in_sub_order = nullptr;
	int* on_ally_base_power_priority = nullptr;
	int* on_ally_modify_atk_priority = nullptr;
	int* on_ally_modify_spa_priority = nullptr;
	int* on_ally_modify_spd_priority = nullptr;
	int* on_attract_priority = nullptr;
	int* on_base_power_priority = nullptr;
	int* on_before_move_priority = nullptr;
	int* on_before_switch_out_priority = nullptr;
	int* on_change_boost_priority = nullptr;
	int* on_damage_priority = nullptr;
	int* on_drag_out_priority = nullptr;
	int* on_effectiveness_priority = nullptr;
	int* on_foe_base_power_priority = nullptr;
	int* on_foe_before_move_priority = nullptr;
	int* on_foe_modify_def_priority = nullptr;
	int* on_foe_modify_spd_priority = nullptr;
	int* on_foe_redirect_target_priority = nullptr;
	int* on_foe_trap_pokemon_priority = nullptr;
	int* on_fractional_priority_priority = nullptr;
	int* on_hit_priority = nullptr;
	int* on_invulnerability_priority = nullptr;
	int* on_modify_accuracy_priority = nullptr;
	int* on_modify_atk_priority = nullptr;
	int* on_modify_crit_ratio_priority = nullptr;
	int* on_modify_def_priority = nullptr;
	int* on_modify_move_priority = nullptr;
	int* on_modify_priority_priority = nullptr;
	int* on_modify_spa_priority = nullptr;
	int* on_modify_spd_priority = nullptr;
	int* on_modify_spe_priority = nullptr;
	int* on_modify_stab_priority = nullptr;
	int* on_modify_type_priority = nullptr;
	int* on_modify_weight_priority = nullptr;
	int* on_redirect_target_priority = nullptr;
	int* on_residual_order = nullptr;
	int* on_residual_priority = nullptr;
	int* on_residual_sub_order = nullptr;
	int* on_source_base_power_priority = nullptr;
	int* on_source_invulnerability_priority = nullptr;
	int* on_source_modify_accuracy_priority = nullptr;
	int* on_source_modify_atk_priority = nullptr;
	int* on_source_modify_damage_priority = nullptr;
	int* on_source_modify_spa_priority = nullptr;
	int* on_switch_in_priority = nullptr;
	int* on_switch_in_sub_order = nullptr;
	int* on_trap_pokemon_priority = nullptr;
	int* on_try_boost_priority = nullptr;
	int* on_try_eat_item_priority = nullptr;
	int* on_try_heal_priority = nullptr;
	int* on_try_hit_priority = nullptr;
	int* on_try_move_priority = nullptr;
	int* on_try_primary_hit_priority = nullptr;
	int* on_type_priority = nullptr;
};
