# Create a temporary input file for the simulator
$input = @"
>start {"formatid":"gen9customgame","seed":[1818,1818,1818,1818]}
>player p1 {"name":"Bot 1","team":[{"name":"calyrex-ice","species":"Calyrex-Ice","item":"Leftovers","ability":"As One (Glastrier)","moves":["glaciallance","leechseed","trickroom","protect"],"nature":"Adamant","gender":"M","evs":{"hp":236,"atk":36,"spd":236},"level":50,"teraType":"Water"},{"name":"miraidon","species":"Miraidon","item":"Choice Specs","ability":"Hadron Engine","moves":["voltswitch","dazzlinggleam","electrodrift","dracometeor"],"nature":"Modest","gender":"M","evs":{"hp":236,"def":52,"spa":124,"spd":68,"spe":28},"level":50,"teraType":"Fairy"},{"name":"ursaluna","species":"Ursaluna","item":"Flame Orb","ability":"Guts","moves":["facade","crunch","headlongrush","protect"],"nature":"Adamant","gender":"M","evs":{"hp":108,"atk":156,"def":4,"spd":116,"spe":124},"level":50,"teraType":"Ghost"},{"name":"volcarona","species":"Volcarona","item":"Rocky Helmet","ability":"Flame Body","moves":["strugglebug","overheat","protect","tailwind"],"nature":"Bold","gender":"M","evs":{"hp":252,"def":196,"spd":60},"level":50,"teraType":"Water"},{"name":"grimmsnarl","species":"Grimmsnarl","item":"Light Clay","ability":"Prankster","moves":["spiritbreak","thunderwave","reflect","lightscreen"],"nature":"Careful","gender":"M","evs":{"hp":236,"atk":4,"def":140,"spd":116,"spe":12},"level":50,"teraType":"Ghost"},{"name":"ironhands","species":"Iron Hands","item":"Assault Vest","ability":"Quark Drive","moves":["fakeout","heavyslam","lowkick","wildcharge"],"nature":"Adamant","gender":"M","evs":{"hp":236,"spd":236,"spe":36},"level":50,"teraType":"Bug"}]}
>player p2 {"name":"Bot 2","team":[{"name":"calyrex-ice","species":"Calyrex-Ice","item":"Leftovers","ability":"As One (Glastrier)","moves":["glaciallance","leechseed","trickroom","protect"],"nature":"Adamant","gender":"M","evs":{"hp":236,"atk":36,"spd":236},"level":50,"teraType":"Water"},{"name":"miraidon","species":"Miraidon","item":"Choice Specs","ability":"Hadron Engine","moves":["voltswitch","dazzlinggleam","electrodrift","dracometeor"],"nature":"Modest","gender":"M","evs":{"hp":236,"def":52,"spa":124,"spd":68,"spe":28},"level":50,"teraType":"Fairy"},{"name":"ursaluna","species":"Ursaluna","item":"Flame Orb","ability":"Guts","moves":["facade","crunch","headlongrush","protect"],"nature":"Adamant","gender":"M","evs":{"hp":108,"atk":156,"def":4,"spd":116,"spe":124},"level":50,"teraType":"Ghost"},{"name":"volcarona","species":"Volcarona","item":"Rocky Helmet","ability":"Flame Body","moves":["strugglebug","overheat","protect","tailwind"],"nature":"Bold","gender":"M","evs":{"hp":252,"def":196,"spd":60},"level":50,"teraType":"Water"},{"name":"grimmsnarl","species":"Grimmsnarl","item":"Light Clay","ability":"Prankster","moves":["spiritbreak","thunderwave","reflect","lightscreen"],"nature":"Careful","gender":"M","evs":{"hp":236,"atk":4,"def":140,"spd":116,"spe":12},"level":50,"teraType":"Ghost"},{"name":"ironhands","species":"Iron Hands","item":"Assault Vest","ability":"Quark Drive","moves":["fakeout","heavyslam","lowkick","wildcharge"],"nature":"Adamant","gender":"M","evs":{"hp":236,"spd":236,"spe":36},"level":50,"teraType":"Bug"}]}
>p1 team 1234
>p2 team 1234
>p1 move 1, move 1
>p2 move 1, move 1
"@

Set-Location pokemon-showdown
$input | node pokemon-showdown simulate-battle > ../ts_output.txt
Set-Location ..
Write-Host "TypeScript output saved to ts_output.txt"
