namespace ApogeeVGC.Sim.Abilities;

public enum AbilityId
{
    AsOneGlastrier,
    HadronEngine,
    Guts,
    FlameBody,
    Prankster,
    QuarkDrive,

    ChillingNeigh,
    Unnerve,
    QuickFeet,

    Overgrow,
    Chlorophyll,
    EarlyBird,
    Bulletproof,
    Swarm,
    Frisk,
    Pickpocket,
    Corrosion,
    NeutralizingGas,
    Klutz,
    IceFace,
    Disguise,
    Multitype,
    Levitate,
    TeraShell,
    AngerPoint,
    PoisonTouch,
    PerishBody,
    Stall,
    MagicBounce,
    Harvest,
    Pickup,
    Stalwart,
    PropellerTail,
    NaturalCure,
    Dancer,
    SheerForce,
    Illusion,

    // New abilities from TS conversion
    Adaptability,
    Aerilate,
    Aftermath,
    AirLock,
    Analytic,
    Blaze,
    Drought,
    MegaLauncher,
    RainDish,
    SolarPower,
    ThickFat,
    ToughClaws,
    Torrent,
    ShieldDust,
    RunAway,
    ShedSkin,
    CompoundEyes,
    TintedLens,
    Sniper,
    KeenEye,
    TangledFeet,
    BigPecks,
    Hustle,
    Intimidate,
    NoGuard,
    Gluttony,
    Static,
    LightningRod,
    SurgeSurfer,
    SandVeil,
    SandRush,
    SnowCloak,
    SlushRush,
    PoisonPoint,
    Rivalry,
    CuteCharm,
    MagicGuard,
    FriendGuard,
    Unaware,
    FlashFire,
    SnowWarning,
    Competitive,
    Infiltrator,
    Stench,
    EffectSpore,
    DrySkin,
    Damp,
    WonderSkin,
    InnerFocus,
    ArenaTrap,
    SandForce,
    TanglingHair,
    HyperCutter,
    ShellArmor,
    Technician,
    Limber,
    Rattled,
    FurCoat,
    CloudNine,
    SwiftSwim,
    VitalSpirit,
    Defiant,
    Justified,
    RockHead,
    WaterAbsorb,
    Synchronize,
    Trace,
    Telepathy,
    Steadfast,
    LiquidOoze,
    StickyHold,
    SkillLink,
    Overcoat,
    CursedBody,
    ShadowTag,
    Sturdy,
    WeakArmor,
    BattleArmor,
    MagnetPull,
    Galvanize,
    Scrappy,
    HydroVeil,
    IceBody,
    Pressure,
    ClearBody,
    MoldBreaker,
    HeavyMetal,
    LightMetal,
    Soundproof,
    Anticipation,
    Illuminate,
    WaterVeil,
    Hydration,
    Oblivious,
    OwnTempo,
    Regenerator,
    QuickDraw,
    PastelVeil,
    PowerOfAlchemy,
    Insomnia,
    Forewarn,
    Reckless,
    StormDrain,
    MistySurge,
        SereneGrace,
        Healer,
        IronFist,
        Filter,
        LeafGuard,
        ParentalBond,
        ScreenCleaner,
        Moxie,
        Imposter,
        CudChew,
        VoltAbsorb,
        Download,
        BattleArmor2,
        FlameBody2,
        Immunity,
        Berserk,
        MarvelScale,
        Multiscale,
        SuperLuck,
        Plus,
        SapSipper,
        HugePower,
        Drizzle,
        SpeedBoost,
        CuriousMedicine,
        Contrary,
        HoneyGather,
        MagmaArmor,
        Moody,
        SuctionCups,
        SandStream,
        Unburden,
        WindRider,
        Pixilate,
        PoisonHeal,
        Truant,
        WonderGuard,
        Normalize,

            // Added for Sableye to Torkoal conversion
            PurePower,
            Minus,
            RoughSkin,
            StrongJaw,
            Simple,
            SolidRock,
            WhiteSmoke,

            // Added for Spoink to Claydol conversion
            ToxicBoost,

                // Added for Lileep to Sealeo conversion
                Forecast,
                ColorChange,
                Protean,
                FlareBoost,
                Refrigerate,

                // Added for Walrein to Deoxys conversion
                DeepSeaTooth,
                DeepSeaScale,
                PrimordialSea,
                DesolateLand,
                DeltaStream,
                AirLock2,
                VictoryStar,
                BadDreams,

                // Added for Shieldon to Drifloon conversion
                FlowerGift,

                // Added for Buneary to Garchomp-Mega conversion
                Heatproof,

                // Added for Magnezone to Gliscor conversion
                MotorDrive,

                // Added for Mamoswine to Uxie conversion
                Sharpness,

                // Added for Mesprit to Shaymin conversion
                SlowStart,

                // Added for Darumaka to Yamask conversion
                ZenMode,
                    GorillaTactics,
                    Mummy,
                    WanderingSpirit,

                        // Added for Cofagrigus to Gothita conversion
                        Defeatist,

                        // Added for Karrablast to Tynamo conversion
                        IronBarbs,

                            // Added for Shelmet to Braviary-Hisui conversion
                            Mimicry,

                                // Added for Reshiram to Genesect conversion
                                Turboblaze,
                                Teravolt,

                                // Added for Gen 6 species (651-700)
                                Magician,
                                GaleWings,
                                FlowerVeil,
                                Symbiosis,
                                GrassPelt,
                                AromaVeil,
                                SweetVeil,
                                StanceChange,
                                    BattleBond,
                                    CheekPouch,

                                        // Added for Gen 6/7 species (701-750)
                                        Gooey,
                                        FairyAura,
                                        DarkAura,
                                        AuraBreak,
                                        PowerConstruct,
                                        LongReach,

                                            // Added for Gen 7 species (726-750)
                                            Stakeout,
                                            Battery,
                                            LiquidVoice,
                                            Schooling,
                                            Merciless,
                                            Stamina,
                                            ToughClaws2,

                                                // Added for Gen 7 species (751-775)
                                                WaterBubble,
                                                Fluffy,
                                                QueenlyMajesty,
                                                Triage,
                                                Receiver,
                                                WimpOut,
                                                EmergencyExit,
                                                WaterCompaction,
                                                InnardsOut,
                                                RksSystem,
                                                ShieldsDown,
                                                Comatose,

                                                    // Added for Gen 7 species (776-800)
                                                    Dazzling,
                                                    Steelworker,
                                                    ElectricSurge,
                                                    PsychicSurge,
                                                    GrassySurge,
                                                    FullMetalBody,
                                                    ShadowShield,
                                                    BeastBoost,
                                                    PrismArmor,
                                                    Neuroforce,

                                                        // Added for Gen 7/8 species (801-825)
                                                        SoulHeart,
                                                        Libero,
                                                            MirrorArmor,

                                                            // Added for Gen 8 species (826-850)
                                                            CottonDown,
                                                            BallFetch,
                                                            SteamEngine,
                                                            Ripen,
                                                            SandSpit,
                                                            GulpMissile,
                                                            PunkRock,

                                                                // Added for Gen 8 species (851-875)
                                                                IceScales,
                                                                PowerSpot,
                                                                HungerSwitch,
                                                                SteelySpirit,

                                                                    // Added for Gen 8 species (876-900)
                                                                    IntrepidSword,
                                                                    DauntlessShield,
                                                                    Transistor,
                                                                    DragonsMaw,
                                                                    GrimNeigh,
                                                                    UnseenFist,
                                                                    AsOneSpectrier,

                                                                        // Added for Gen 9 species (901-925)
                                                                        MindsEye,
                                                                        LingeringAroma,
                                                                        SeedSower,
                                                                        MyceliumMight,
                                                                        WellBakedBody,

                                                                        // Added for Gen 9 species (926-950)
                                                                        PurifyingSalt,
                                                                        Electromorphosis,
                                                                        AngerShell,
                                                                        GuardDog,
                                                                        WindPower,

                                                                            // Added for Gen 9 species (951-975)
                                                                            Opportunist,
                                                                            ZeroToHero,
                                                                            EarthEater,
                                                                            ToxicDebris,
                                                                            Costar,
                                                                            Commander,
                                                                            RockyPayload,

                                                                                // Added for Gen 9 species (976-1000)
                                                                                ArmorTail,
                                                                                SupremeOverlord,
                                                                                Protosynthesis,
                                                                                ThermalExchange,
                                                                                GoodAsGold,

                                                                                // Added for Gen 9 species (1001-1025)
                                                                                TabletsOfRuin,
                                                                                SwordOfRuin,
                                                                                VesselOfRuin,
                                                                                BeadsOfRuin,
                                                                                OrichalcumPulse,
                                                                                SupersweetSyrup,
                                                                                Hospitality,
                                                                                ToxicChain,
                                                                                        EmbodyAspectTeal,
                                                                                        EmbodyAspectWellspring,
                                                                                        EmbodyAspectHearthflame,
                                                                                        EmbodyAspectCornerstone,
                                                                                        TeraShift,
                                                                                        TeraformZero,
                                                                                        PoisonPuppeteer,

                                                                                        None,
                                                                                    }