namespace ApogeeVGC.Sim.Abilities;

public enum AbilityId
{
    AsOneGlastrier,
    HadronEngine,
    Guts,
    FlameBody,
    Prankster,
    QuarkDrive,

    ChillingNeigh,
    Unnerve,
    QuickFeet,

    Overgrow,
    Chlorophyll,
    EarlyBird,
    Bulletproof,
    Swarm,
    Frisk,
    Pickpocket,
    Corrosion,
    NeutralizingGas,
    Klutz,
    IceFace,
    Disguise,
    Multitype,
    Levitate,
    TeraShell,
    AngerPoint,
    PoisonTouch,
    PerishBody,
    Stall,
    MagicBounce,
    Harvest,
    Pickup,
    Stalwart,
    PropellerTail,
    NaturalCure,
    Dancer,
    SheerForce,
    Illusion,

    // New abilities from TS conversion
    Adaptability,
    Aerilate,
    Aftermath,
    AirLock,
    Analytic,
    Blaze,
    Drought,
    MegaLauncher,
    RainDish,
    SolarPower,
    ThickFat,
    ToughClaws,
    Torrent,
    ShieldDust,
    RunAway,
    ShedSkin,
    CompoundEyes,
    TintedLens,
    Sniper,
    KeenEye,
    TangledFeet,
    BigPecks,
    Hustle,
    Intimidate,
    NoGuard,
    Gluttony,
    Static,
    LightningRod,
    SurgeSurfer,
    SandVeil,
    SandRush,
    SnowCloak,
    SlushRush,
    PoisonPoint,
    Rivalry,
    CuteCharm,
    MagicGuard,
    FriendGuard,
    Unaware,
    FlashFire,
    SnowWarning,
    Competitive,
    Infiltrator,
    Stench,
    EffectSpore,
    DrySkin,
    Damp,
    WonderSkin,
    InnerFocus,
    ArenaTrap,
    SandForce,
    TanglingHair,
    HyperCutter,
    ShellArmor,
    Technician,
    Limber,
    Rattled,
    FurCoat,
    CloudNine,
    SwiftSwim,
    VitalSpirit,
    Defiant,
    Justified,
    RockHead,
    WaterAbsorb,
    Synchronize,
    Trace,
    Telepathy,
    Steadfast,
    LiquidOoze,
    StickyHold,
    SkillLink,
    Overcoat,
    CursedBody,
    ShadowTag,
    Sturdy,
    WeakArmor,
    BattleArmor,
    MagnetPull,
    Galvanize,
    Scrappy,
    HydroVeil,
    IceBody,
    Pressure,
    ClearBody,
    MoldBreaker,
    HeavyMetal,
    LightMetal,
    Soundproof,
    Anticipation,
    Illuminate,
    WaterVeil,
    Hydration,
    Oblivious,
    OwnTempo,
    Regenerator,
    QuickDraw,
    PastelVeil,
    PowerOfAlchemy,
    Insomnia,
    Forewarn,
    Reckless,
    StormDrain,
    MistySurge,
        SereneGrace,
        Healer,
        IronFist,
        Filter,
        LeafGuard,
        ParentalBond,
        ScreenCleaner,
        Moxie,
        Imposter,
        CudChew,
        VoltAbsorb,
        Download,
        BattleArmor2,
        FlameBody2,
        Immunity,
        Berserk,
        MarvelScale,
        Multiscale,
        SuperLuck,
        Plus,
        SapSipper,
        HugePower,
        Drizzle,
        SpeedBoost,
        CuriousMedicine,
        Contrary,
        HoneyGather,
        MagmaArmor,
        Moody,
        SuctionCups,
        SandStream,
        Unburden,
        WindRider,
        Pixilate,
        PoisonHeal,
        Truant,
        WonderGuard,
        Normalize,

            // Added for Sableye to Torkoal conversion
            PurePower,
            Minus,
            RoughSkin,
            StrongJaw,
            Simple,
            SolidRock,
            WhiteSmoke,

            // Added for Spoink to Claydol conversion
            ToxicBoost,

                // Added for Lileep to Sealeo conversion
                Forecast,
                ColorChange,
                Protean,
                FlareBoost,
                Refrigerate,

                // Added for Walrein to Deoxys conversion
                DeepSeaTooth,
                DeepSeaScale,
                PrimordialSea,
                DesolateLand,
                DeltaStream,
                AirLock2,
                VictoryStar,
                BadDreams,

                // Added for Shieldon to Drifloon conversion
                FlowerGift,

                // Added for Buneary to Garchomp-Mega conversion
                Heatproof,

                // Added for Magnezone to Gliscor conversion
                MotorDrive,

                None,
            }