using ApogeeVGC.Sim.Events;
using ApogeeVGC.Sim.Events.Handlers.EventMethods;
using ApogeeVGC.Sim.Events.Handlers.FieldEventMethods;
using ApogeeVGC.Sim.Events.Handlers.PokemonEventMethods;

namespace ApogeeVGC.Sim.Conditions;

public partial record Condition : IPokemonEventMethodsV2
{
    public OnDamagingHitEventInfo? OnDamagingHit { get; init; }
    public OnEmergencyExitEventInfo? OnEmergencyExit { get; init; }
    public OnAfterEachBoostEventInfo? OnAfterEachBoost { get; init; }
    public OnAfterHitEventInfo? OnAfterHit { get; init; }
    public OnAfterMegaEventInfo? OnAfterMega { get; init; }
    public OnAfterSetStatusEventInfo? OnAfterSetStatus { get; init; }
    public OnAfterSubDamageEventInfo? OnAfterSubDamage { get; init; }
    public OnAfterSwitchInSelfEventInfo? OnAfterSwitchInSelf { get; init; }
    public OnAfterTerastallizationEventInfo? OnAfterTerastallization { get; init; }
    public OnAfterUseItemEventInfo? OnAfterUseItem { get; init; }
    public OnAfterTakeItemEventInfo? OnAfterTakeItem { get; init; }
    public OnAfterBoostEventInfo? OnAfterBoost { get; init; }
    public OnAfterFaintEventInfo? OnAfterFaint { get; init; }
    public OnAfterMoveSecondarySelfEventInfo? OnAfterMoveSecondarySelf { get; init; }
    public OnAfterMoveSecondaryEventInfo? OnAfterMoveSecondary { get; init; }
    public OnAfterMoveEventInfo? OnAfterMove { get; init; }
    public OnAfterMoveSelfEventInfo? OnAfterMoveSelf { get; init; }
    public OnAttractEventInfo? OnAttract { get; init; }
    public OnAccuracyEventInfo? OnAccuracy { get; init; }
    public OnBasePowerEventInfo? OnBasePower { get; init; }
    public OnBeforeFaintEventInfo? OnBeforeFaint { get; init; }
    public OnBeforeMoveEventInfo? OnBeforeMove { get; init; }
    public OnBeforeSwitchInEventInfo? OnBeforeSwitchIn { get; init; }
    public OnBeforeSwitchOutEventInfo? OnBeforeSwitchOut { get; init; }
    public OnBeforeTurnEventInfo? OnBeforeTurn { get; init; }
    public OnChangeBoostEventInfo? OnChangeBoost { get; init; }
    public OnTryBoostEventInfo? OnTryBoost { get; init; }
    public OnChargeMoveEventInfo? OnChargeMove { get; init; }
    public OnCriticalHitEventInfo? OnCriticalHit { get; init; }
    public OnDamageEventInfo? OnDamage { get; init; }
    public OnDeductPpEventInfo? OnDeductPp { get; init; }
    public OnDisableMoveEventInfo? OnDisableMove { get; init; }
    public OnDragOutEventInfo? OnDragOut { get; init; }
    public OnEatItemEventInfo? OnEatItem { get; init; }
    public OnEffectivenessEventInfo? OnEffectiveness { get; init; }
    public OnEntryHazardEventInfo? OnEntryHazard { get; init; }
    public OnFaintEventInfo? OnFaint { get; init; }
    public OnFlinchEventInfo? OnFlinch { get; init; }
    public OnFractionalPriorityEventInfo? OnFractionalPriority { get; init; }
    public OnHitEventInfo? OnHit { get; init; }
    public OnImmunityEventInfo? OnImmunity { get; init; }
    public OnLockMoveEventInfo? OnLockMove { get; init; }
    public OnMaybeTrapPokemonEventInfo? OnMaybeTrapPokemon { get; init; }
    public OnModifyAccuracyEventInfo? OnModifyAccuracy { get; init; }
    public OnModifyAtkEventInfo? OnModifyAtk { get; init; }
    public OnModifyBoostEventInfo? OnModifyBoost { get; init; }
    public OnModifyCritRatioEventInfo? OnModifyCritRatio { get; init; }
    public OnModifyDamageEventInfo? OnModifyDamage { get; init; }
    public OnModifyDefEventInfo? OnModifyDef { get; init; }
    public OnModifyMoveEventInfo? OnModifyMove { get; init; }
    public OnModifyPriorityEventInfo? OnModifyPriority { get; init; }
    public OnModifySecondariesEventInfo? OnModifySecondaries { get; init; }
    public OnModifyTypeEventInfo? OnModifyType { get; init; }
    public OnModifyTargetEventInfo? OnModifyTarget { get; init; }
    public OnModifySpAEventInfo? OnModifySpA { get; init; }
    public OnModifySpDEventInfo? OnModifySpD { get; init; }
    public OnModifySpeEventInfo? OnModifySpe { get; init; }
    public OnModifyStabEventInfo? OnModifyStab { get; init; }
    public OnModifyWeightEventInfo? OnModifyWeight { get; init; }
    public OnMoveAbortedEventInfo? OnMoveAborted { get; init; }
    public OnNegateImmunityEventInfo? OnNegateImmunity { get; init; }
    public OnOverrideActionEventInfo? OnOverrideAction { get; init; }
    public OnPrepareHitEventInfo? OnPrepareHit { get; init; }
    public OnPseudoWeatherChangeEventInfo? OnPseudoWeatherChange { get; init; }
    public OnRedirectTargetEventInfo? OnRedirectTarget { get; init; }
    public OnResidualEventInfo? OnResidual { get; init; }
    public OnSetAbilityEventInfo? OnSetAbility { get; init; }
    public OnSetStatusEventInfo? OnSetStatus { get; init; }
    public OnSetWeatherEventInfo? OnSetWeather { get; init; }
    public OnSideConditionStartEventInfo? OnSideConditionStart { get; init; }
    public OnStallMoveEventInfo? OnStallMove { get; init; }
    public OnSwitchInEventInfo? OnSwitchIn { get; init; }
    public OnSwitchOutEventInfo? OnSwitchOut { get; init; }
    public OnSwapEventInfo? OnSwap { get; init; }
    public OnTakeItemEventInfo? OnTakeItem { get; init; }
    public OnWeatherChangeEventInfo? OnWeatherChange { get; init; }
    public OnTerrainChangeEventInfo? OnTerrainChange { get; init; }
    public OnTrapPokemonEventInfo? OnTrapPokemon { get; init; }
    public OnTryAddVolatileEventInfo? OnTryAddVolatile { get; init; }
    public OnTryEatItemEventInfo? OnTryEatItem { get; init; }
    public OnTryHealEventInfo? OnTryHeal { get; init; }
    public OnTryHitEventInfo? OnTryHit { get; init; }
    public OnTryHitFieldEventInfo? OnTryHitField { get; init; }
    public OnTryHitSideEventInfo? OnTryHitSide { get; init; }
    public OnInvulnerabilityEventInfo? OnInvulnerability { get; init; }
    public OnTryMoveEventInfo? OnTryMove { get; init; }
    public OnTryPrimaryHitEventInfo? OnTryPrimaryHit { get; init; }
    public OnTypeEventInfo? OnType { get; init; }
    public OnUseItemEventInfo? OnUseItem { get; init; }
    public OnUpdateEventInfo? OnUpdate { get; init; }
    public OnWeatherEventInfo? OnWeather { get; init; }
    public OnWeatherModifyDamageEventInfo? OnWeatherModifyDamage { get; init; }
    public OnModifyDamagePhase1EventInfo? OnModifyDamagePhase1 { get; init; }
    public OnModifyDamagePhase2EventInfo? OnModifyDamagePhase2 { get; init; }
    public OnFoeDamagingHitEventInfo? OnFoeDamagingHit { get; init; }
    public OnFoeAfterEachBoostEventInfo? OnFoeAfterEachBoost { get; init; }
    public OnFoeAfterHitEventInfo? OnFoeAfterHit { get; init; }
    public OnFoeAfterSetStatusEventInfo? OnFoeAfterSetStatus { get; init; }
    public OnFoeAfterSubDamageEventInfo? OnFoeAfterSubDamage { get; init; }
    public OnFoeAfterSwitchInSelfEventInfo? OnFoeAfterSwitchInSelf { get; init; }
    public OnFoeAfterUseItemEventInfo? OnFoeAfterUseItem { get; init; }
    public OnFoeAfterBoostEventInfo? OnFoeAfterBoost { get; init; }
    public OnFoeAfterFaintEventInfo? OnFoeAfterFaint { get; init; }
    public OnFoeAfterMoveSecondarySelfEventInfo? OnFoeAfterMoveSecondarySelf { get; init; }
    public OnFoeAfterMoveSecondaryEventInfo? OnFoeAfterMoveSecondary { get; init; }
    public OnFoeAfterMoveEventInfo? OnFoeAfterMove { get; init; }
    public OnFoeAfterMoveSelfEventInfo? OnFoeAfterMoveSelf { get; init; }
    public OnFoeAttractEventInfo? OnFoeAttract { get; init; }
    public OnFoeAccuracyEventInfo? OnFoeAccuracy { get; init; }
    public OnFoeBasePowerEventInfo? OnFoeBasePower { get; init; }
    public OnFoeBeforeFaintEventInfo? OnFoeBeforeFaint { get; init; }
    public OnFoeBeforeMoveEventInfo? OnFoeBeforeMove { get; init; }
    public OnFoeBeforeSwitchInEventInfo? OnFoeBeforeSwitchIn { get; init; }
    public OnFoeBeforeSwitchOutEventInfo? OnFoeBeforeSwitchOut { get; init; }
    public OnFoeTryBoostEventInfo? OnFoeTryBoost { get; init; }
    public OnFoeChargeMoveEventInfo? OnFoeChargeMove { get; init; }
    public OnFoeCriticalHitEventInfo? OnFoeCriticalHit { get; init; }
    public OnFoeDamageEventInfo? OnFoeDamage { get; init; }
    public OnFoeDeductPpEventInfo? OnFoeDeductPp { get; init; }
    public OnFoeDisableMoveEventInfo? OnFoeDisableMove { get; init; }
    public OnFoeDragOutEventInfo? OnFoeDragOut { get; init; }
    public OnFoeEatItemEventInfo? OnFoeEatItem { get; init; }
    public OnFoeEffectivenessEventInfo? OnFoeEffectiveness { get; init; }
    public OnFoeFaintEventInfo? OnFoeFaint { get; init; }
    public OnFoeFlinchEventInfo? OnFoeFlinch { get; init; }
    public OnFoeHitEventInfo? OnFoeHit { get; init; }
    public OnFoeImmunityEventInfo? OnFoeImmunity { get; init; }
    public OnFoeLockMoveEventInfo? OnFoeLockMove { get; init; }
    public OnFoeMaybeTrapPokemonEventInfo? OnFoeMaybeTrapPokemon { get; init; }
    public OnFoeModifyAccuracyEventInfo? OnFoeModifyAccuracy { get; init; }
    public OnFoeModifyAtkEventInfo? OnFoeModifyAtk { get; init; }
    public OnFoeModifyBoostEventInfo? OnFoeModifyBoost { get; init; }
    public OnFoeModifyCritRatioEventInfo? OnFoeModifyCritRatio { get; init; }
    public OnFoeModifyDamageEventInfo? OnFoeModifyDamage { get; init; }
    public OnFoeModifyDefEventInfo? OnFoeModifyDef { get; init; }
    public OnFoeModifyMoveEventInfo? OnFoeModifyMove { get; init; }
    public OnFoeModifyPriorityEventInfo? OnFoeModifyPriority { get; init; }
    public OnFoeModifySecondariesEventInfo? OnFoeModifySecondaries { get; init; }
    public OnFoeModifySpAEventInfo? OnFoeModifySpA { get; init; }
    public OnFoeModifySpDEventInfo? OnFoeModifySpD { get; init; }
    public OnFoeModifySpeEventInfo? OnFoeModifySpe { get; init; }
    public OnFoeModifyStabEventInfo? OnFoeModifyStab { get; init; }
    public OnFoeModifyTypeEventInfo? OnFoeModifyType { get; init; }
    public OnFoeModifyTargetEventInfo? OnFoeModifyTarget { get; init; }
    public OnFoeModifyWeightEventInfo? OnFoeModifyWeight { get; init; }
    public OnFoeMoveAbortedEventInfo? OnFoeMoveAborted { get; init; }
    public OnFoeNegateImmunityEventInfo? OnFoeNegateImmunity { get; init; }
    public OnFoeOverrideActionEventInfo? OnFoeOverrideAction { get; init; }
    public OnFoePrepareHitEventInfo? OnFoePrepareHit { get; init; }
    public OnFoeRedirectTargetEventInfo? OnFoeRedirectTarget { get; init; }
    public OnFoeResidualEventInfo? OnFoeResidual { get; init; }
    public OnFoeSetAbilityEventInfo? OnFoeSetAbility { get; init; }
    public OnFoeSetStatusEventInfo? OnFoeSetStatus { get; init; }
    public OnFoeSetWeatherEventInfo? OnFoeSetWeather { get; init; }
    public OnFoeStallMoveEventInfo? OnFoeStallMove { get; init; }
    public OnFoeSwitchOutEventInfo? OnFoeSwitchOut { get; init; }
    public OnFoeTakeItemEventInfo? OnFoeTakeItem { get; init; }
    public OnFoeTerrainEventInfo? OnFoeTerrain { get; init; }
    public OnFoeTrapPokemonEventInfo? OnFoeTrapPokemon { get; init; }
    public OnFoeTryAddVolatileEventInfo? OnFoeTryAddVolatile { get; init; }
    public OnFoeTryEatItemEventInfo? OnFoeTryEatItem { get; init; }
    public OnFoeTryHealEventInfo? OnFoeTryHeal { get; init; }
    public OnFoeTryHitEventInfo? OnFoeTryHit { get; init; }
    public OnFoeTryHitFieldEventInfo? OnFoeTryHitField { get; init; }
    public OnFoeTryHitSideEventInfo? OnFoeTryHitSide { get; init; }
    public OnFoeInvulnerabilityEventInfo? OnFoeInvulnerability { get; init; }
    public OnFoeTryMoveEventInfo? OnFoeTryMove { get; init; }
    public OnFoeTryPrimaryHitEventInfo? OnFoeTryPrimaryHit { get; init; }
    public OnFoeTypeEventInfo? OnFoeType { get; init; }
    public OnFoeWeatherModifyDamageEventInfo? OnFoeWeatherModifyDamage { get; init; }
    public OnFoeModifyDamagePhase1EventInfo? OnFoeModifyDamagePhase1 { get; init; }
    public OnFoeModifyDamagePhase2EventInfo? OnFoeModifyDamagePhase2 { get; init; }
    public OnSourceDamagingHitEventInfo? OnSourceDamagingHit { get; init; }
    public OnSourceAfterEachBoostEventInfo? OnSourceAfterEachBoost { get; init; }
    public OnSourceAfterHitEventInfo? OnSourceAfterHit { get; init; }
    public OnSourceAfterSetStatusEventInfo? OnSourceAfterSetStatus { get; init; }
    public OnSourceAfterSubDamageEventInfo? OnSourceAfterSubDamage { get; init; }
    public OnSourceAfterSwitchInSelfEventInfo? OnSourceAfterSwitchInSelf { get; init; }
    public OnSourceAfterUseItemEventInfo? OnSourceAfterUseItem { get; init; }
    public OnSourceAfterBoostEventInfo? OnSourceAfterBoost { get; init; }
    public OnSourceAfterFaintEventInfo? OnSourceAfterFaint { get; init; }
    public OnSourceAfterMoveSecondarySelfEventInfo? OnSourceAfterMoveSecondarySelf { get; init; }
    public OnSourceAfterMoveSecondaryEventInfo? OnSourceAfterMoveSecondary { get; init; }
    public OnSourceAfterMoveEventInfo? OnSourceAfterMove { get; init; }
    public OnSourceAfterMoveSelfEventInfo? OnSourceAfterMoveSelf { get; init; }
    public OnSourceAttractEventInfo? OnSourceAttract { get; init; }
    public OnSourceAccuracyEventInfo? OnSourceAccuracy { get; init; }
    public OnSourceBasePowerEventInfo? OnSourceBasePower { get; init; }
    public OnSourceBeforeFaintEventInfo? OnSourceBeforeFaint { get; init; }
    public OnSourceBeforeMoveEventInfo? OnSourceBeforeMove { get; init; }
    public OnSourceBeforeSwitchInEventInfo? OnSourceBeforeSwitchIn { get; init; }
    public OnSourceBeforeSwitchOutEventInfo? OnSourceBeforeSwitchOut { get; init; }
    public OnSourceTryBoostEventInfo? OnSourceTryBoost { get; init; }
    public OnSourceChargeMoveEventInfo? OnSourceChargeMove { get; init; }
    public OnSourceCriticalHitEventInfo? OnSourceCriticalHit { get; init; }
    public OnSourceDamageEventInfo? OnSourceDamage { get; init; }
    public OnSourceDeductPpEventInfo? OnSourceDeductPp { get; init; }
    public OnSourceDisableMoveEventInfo? OnSourceDisableMove { get; init; }
    public OnSourceDragOutEventInfo? OnSourceDragOut { get; init; }
    public OnSourceEatItemEventInfo? OnSourceEatItem { get; init; }
    public OnSourceEffectivenessEventInfo? OnSourceEffectiveness { get; init; }
    public OnSourceFaintEventInfo? OnSourceFaint { get; init; }
    public OnSourceFlinchEventInfo? OnSourceFlinch { get; init; }
    public OnSourceHitEventInfo? OnSourceHit { get; init; }
    public OnSourceImmunityEventInfo? OnSourceImmunity { get; init; }
    public OnSourceLockMoveEventInfo? OnSourceLockMove { get; init; }
    public OnSourceMaybeTrapPokemonEventInfo? OnSourceMaybeTrapPokemon { get; init; }
    public OnSourceModifyAccuracyEventInfo? OnSourceModifyAccuracy { get; init; }
    public OnSourceModifyAtkEventInfo? OnSourceModifyAtk { get; init; }
    public OnSourceModifyBoostEventInfo? OnSourceModifyBoost { get; init; }
    public OnSourceModifyCritRatioEventInfo? OnSourceModifyCritRatio { get; init; }
    public OnSourceModifyDamageEventInfo? OnSourceModifyDamage { get; init; }
    public OnSourceModifyDefEventInfo? OnSourceModifyDef { get; init; }
    public OnSourceModifyMoveEventInfo? OnSourceModifyMove { get; init; }
    public OnSourceModifyPriorityEventInfo? OnSourceModifyPriority { get; init; }
    public OnSourceModifySecondariesEventInfo? OnSourceModifySecondaries { get; init; }
    public OnSourceModifySpAEventInfo? OnSourceModifySpA { get; init; }
    public OnSourceModifySpDEventInfo? OnSourceModifySpD { get; init; }
    public OnSourceModifySpeEventInfo? OnSourceModifySpe { get; init; }
    public OnSourceModifyStabEventInfo? OnSourceModifyStab { get; init; }
    public OnSourceModifyTypeEventInfo? OnSourceModifyType { get; init; }
    public OnSourceModifyTargetEventInfo? OnSourceModifyTarget { get; init; }
    public OnSourceModifyWeightEventInfo? OnSourceModifyWeight { get; init; }
    public OnSourceMoveAbortedEventInfo? OnSourceMoveAborted { get; init; }
    public OnSourceNegateImmunityEventInfo? OnSourceNegateImmunity { get; init; }
    public OnSourceOverrideActionEventInfo? OnSourceOverrideAction { get; init; }
    public OnSourcePrepareHitEventInfo? OnSourcePrepareHit { get; init; }
    public OnSourceRedirectTargetEventInfo? OnSourceRedirectTarget { get; init; }
    public OnSourceResidualEventInfo? OnSourceResidual { get; init; }
    public OnSourceSetAbilityEventInfo? OnSourceSetAbility { get; init; }
    public OnSourceSetStatusEventInfo? OnSourceSetStatus { get; init; }
    public OnSourceSetWeatherEventInfo? OnSourceSetWeather { get; init; }
    public OnSourceStallMoveEventInfo? OnSourceStallMove { get; init; }
    public OnSourceSwitchOutEventInfo? OnSourceSwitchOut { get; init; }
    public OnSourceTakeItemEventInfo? OnSourceTakeItem { get; init; }
    public OnSourceTerrainEventInfo? OnSourceTerrain { get; init; }
    public OnSourceTrapPokemonEventInfo? OnSourceTrapPokemon { get; init; }
    public OnSourceTryAddVolatileEventInfo? OnSourceTryAddVolatile { get; init; }
    public OnSourceTryEatItemEventInfo? OnSourceTryEatItem { get; init; }
    public OnSourceTryHealEventInfo? OnSourceTryHeal { get; init; }
    public OnSourceTryHitEventInfo? OnSourceTryHit { get; init; }
    public OnSourceTryHitFieldEventInfo? OnSourceTryHitField { get; init; }
    public OnSourceTryHitSideEventInfo? OnSourceTryHitSide { get; init; }
    public OnSourceInvulnerabilityEventInfo? OnSourceInvulnerability { get; init; }
    public OnSourceTryMoveEventInfo? OnSourceTryMove { get; init; }
    public OnSourceTryPrimaryHitEventInfo? OnSourceTryPrimaryHit { get; init; }
    public OnSourceTypeEventInfo? OnSourceType { get; init; }
    public OnSourceWeatherModifyDamageEventInfo? OnSourceWeatherModifyDamage { get; init; }
    public OnSourceModifyDamagePhase1EventInfo? OnSourceModifyDamagePhase1 { get; init; }
    public OnSourceModifyDamagePhase2EventInfo? OnSourceModifyDamagePhase2 { get; init; }
    public OnAnyDamagingHitEventInfo? OnAnyDamagingHit { get; init; }
    public OnAnyAfterEachBoostEventInfo? OnAnyAfterEachBoost { get; init; }
    public OnAnyAfterHitEventInfo? OnAnyAfterHit { get; init; }
    public OnAnyAfterSetStatusEventInfo? OnAnyAfterSetStatus { get; init; }
    public OnAnyAfterSubDamageEventInfo? OnAnyAfterSubDamage { get; init; }
    public OnAnyAfterSwitchInSelfEventInfo? OnAnyAfterSwitchInSelf { get; init; }
    public OnAnyAfterUseItemEventInfo? OnAnyAfterUseItem { get; init; }
    public OnAnyAfterBoostEventInfo? OnAnyAfterBoost { get; init; }
    public OnAnyAfterFaintEventInfo? OnAnyAfterFaint { get; init; }
    public OnAnyAfterMegaEventInfo? OnAnyAfterMega { get; init; }
    public OnAnyAfterMoveSecondarySelfEventInfo? OnAnyAfterMoveSecondarySelf { get; init; }
    public OnAnyAfterMoveSecondaryEventInfo? OnAnyAfterMoveSecondary { get; init; }
    public OnAnyAfterMoveEventInfo? OnAnyAfterMove { get; init; }
    public OnAnyAfterMoveSelfEventInfo? OnAnyAfterMoveSelf { get; init; }
    public OnAnyAfterTerastallizationEventInfo? OnAnyAfterTerastallization { get; init; }
    public OnAnyAttractEventInfo? OnAnyAttract { get; init; }
    public OnAnyAccuracyEventInfo? OnAnyAccuracy { get; init; }
    public OnAnyBasePowerEventInfo? OnAnyBasePower { get; init; }
    public OnAnyBeforeFaintEventInfo? OnAnyBeforeFaint { get; init; }
    public OnAnyBeforeMoveEventInfo? OnAnyBeforeMove { get; init; }
    public OnAnyBeforeSwitchInEventInfo? OnAnyBeforeSwitchIn { get; init; }
    public OnAnyBeforeSwitchOutEventInfo? OnAnyBeforeSwitchOut { get; init; }
    public OnAnyTryBoostEventInfo? OnAnyTryBoost { get; init; }
    public OnAnyChargeMoveEventInfo? OnAnyChargeMove { get; init; }
    public OnAnyCriticalHitEventInfo? OnAnyCriticalHit { get; init; }
    public OnAnyDamageEventInfo? OnAnyDamage { get; init; }
    public OnAnyDeductPpEventInfo? OnAnyDeductPp { get; init; }
    public OnAnyDisableMoveEventInfo? OnAnyDisableMove { get; init; }
    public OnAnyDragOutEventInfo? OnAnyDragOut { get; init; }
    public OnAnyEatItemEventInfo? OnAnyEatItem { get; init; }
    public OnAnyEffectivenessEventInfo? OnAnyEffectiveness { get; init; }
    public OnAnyFaintEventInfo? OnAnyFaint { get; init; }
    public OnAnyFlinchEventInfo? OnAnyFlinch { get; init; }
    public OnAnyHitEventInfo? OnAnyHit { get; init; }
    public OnAnyImmunityEventInfo? OnAnyImmunity { get; init; }
    public OnAnyLockMoveEventInfo? OnAnyLockMove { get; init; }
    public OnAnyMaybeTrapPokemonEventInfo? OnAnyMaybeTrapPokemon { get; init; }
    public OnAnyModifyAccuracyEventInfo? OnAnyModifyAccuracy { get; init; }
    public OnAnyModifyAtkEventInfo? OnAnyModifyAtk { get; init; }
    public OnAnyModifyBoostEventInfo? OnAnyModifyBoost { get; init; }
    public OnAnyModifyCritRatioEventInfo? OnAnyModifyCritRatio { get; init; }
    public OnAnyModifyDamageEventInfo? OnAnyModifyDamage { get; init; }
    public OnAnyModifyDefEventInfo? OnAnyModifyDef { get; init; }
    public OnAnyModifyMoveEventInfo? OnAnyModifyMove { get; init; }
    public OnAnyModifyPriorityEventInfo? OnAnyModifyPriority { get; init; }
    public OnAnyModifySecondariesEventInfo? OnAnyModifySecondaries { get; init; }
    public OnAnyModifySpAEventInfo? OnAnyModifySpA { get; init; }
    public OnAnyModifySpDEventInfo? OnAnyModifySpD { get; init; }
    public OnAnyModifySpeEventInfo? OnAnyModifySpe { get; init; }
    public OnAnyModifyStabEventInfo? OnAnyModifyStab { get; init; }
    public OnAnyModifyTypeEventInfo? OnAnyModifyType { get; init; }
    public OnAnyModifyTargetEventInfo? OnAnyModifyTarget { get; init; }
    public OnAnyModifyWeightEventInfo? OnAnyModifyWeight { get; init; }
    public OnAnyMoveAbortedEventInfo? OnAnyMoveAborted { get; init; }
    public OnAnyNegateImmunityEventInfo? OnAnyNegateImmunity { get; init; }
    public OnAnyOverrideActionEventInfo? OnAnyOverrideAction { get; init; }
    public OnAnyPrepareHitEventInfo? OnAnyPrepareHit { get; init; }
    public OnAnyPseudoWeatherChangeEventInfo? OnAnyPseudoWeatherChange { get; init; }
    public OnAnyRedirectTargetEventInfo? OnAnyRedirectTarget { get; init; }
    public OnAnyResidualEventInfo? OnAnyResidual { get; init; }
    public OnAnySetAbilityEventInfo? OnAnySetAbility { get; init; }
    public OnAnySetStatusEventInfo? OnAnySetStatus { get; init; }
    public OnAnySetWeatherEventInfo? OnAnySetWeather { get; init; }
    public OnAnyStallMoveEventInfo? OnAnyStallMove { get; init; }
    public OnAnySwitchInEventInfo? OnAnySwitchIn { get; init; }
    public OnAnySwitchOutEventInfo? OnAnySwitchOut { get; init; }
    public OnAnyTakeItemEventInfo? OnAnyTakeItem { get; init; }
    public OnAnyTerrainEventInfo? OnAnyTerrain { get; init; }
    public OnAnyTrapPokemonEventInfo? OnAnyTrapPokemon { get; init; }
    public OnAnyTryAddVolatileEventInfo? OnAnyTryAddVolatile { get; init; }
    public OnAnyTryEatItemEventInfo? OnAnyTryEatItem { get; init; }
    public OnAnyTryHealEventInfo? OnAnyTryHeal { get; init; }
    public OnAnyTryHitEventInfo? OnAnyTryHit { get; init; }
    public OnAnyTryHitFieldEventInfo? OnAnyTryHitField { get; init; }
    public OnAnyTryHitSideEventInfo? OnAnyTryHitSide { get; init; }
    public OnAnyInvulnerabilityEventInfo? OnAnyInvulnerability { get; init; }
    public OnAnyTryMoveEventInfo? OnAnyTryMove { get; init; }
    public OnAnyTryPrimaryHitEventInfo? OnAnyTryPrimaryHit { get; init; }
    public OnAnyTypeEventInfo? OnAnyType { get; init; }
    public OnAnyWeatherModifyDamageEventInfo? OnAnyWeatherModifyDamage { get; init; }
    public OnAnyModifyDamagePhase1EventInfo? OnAnyModifyDamagePhase1 { get; init; }
    public OnAnyModifyDamagePhase2EventInfo? OnAnyModifyDamagePhase2 { get; init; }
    public OnFieldStartEventInfo? OnFieldStart { get; init; }
    public OnFieldRestartEventInfo? OnFieldRestart { get; init; }
    public OnFieldResidualEventInfo? OnFieldResidual { get; init; }
    public OnFieldEndEventInfo? OnFieldEnd { get; init; }
    public OnAllyDamagingHitEventInfo? OnAllyDamagingHit { get; init; }
    public OnAllyAfterEachBoostEventInfo? OnAllyAfterEachBoost { get; init; }
    public OnAllyAfterHitEventInfo? OnAllyAfterHit { get; init; }
    public OnAllyAfterSetStatusEventInfo? OnAllyAfterSetStatus { get; init; }
    public OnAllyAfterSubDamageEventInfo? OnAllyAfterSubDamage { get; init; }
    public OnAllyAfterSwitchInSelfEventInfo? OnAllyAfterSwitchInSelf { get; init; }
    public OnAllyAfterUseItemEventInfo? OnAllyAfterUseItem { get; init; }
    public OnAllyAfterBoostEventInfo? OnAllyAfterBoost { get; init; }
    public OnAllyAfterFaintEventInfo? OnAllyAfterFaint { get; init; }
    public OnAllyAfterMoveSecondarySelfEventInfo? OnAllyAfterMoveSecondarySelf { get; init; }
    public OnAllyAfterMoveSecondaryEventInfo? OnAllyAfterMoveSecondary { get; init; }
    public OnAllyAfterMoveEventInfo? OnAllyAfterMove { get; init; }
    public OnAllyAfterMoveSelfEventInfo? OnAllyAfterMoveSelf { get; init; }
    public OnAllyAttractEventInfo? OnAllyAttract { get; init; }
    public OnAllyAccuracyEventInfo? OnAllyAccuracy { get; init; }
    public OnAllyBasePowerEventInfo? OnAllyBasePower { get; init; }
    public OnAllyBeforeFaintEventInfo? OnAllyBeforeFaint { get; init; }
    public OnAllyBeforeMoveEventInfo? OnAllyBeforeMove { get; init; }
    public OnAllyBeforeSwitchInEventInfo? OnAllyBeforeSwitchIn { get; init; }
    public OnAllyBeforeSwitchOutEventInfo? OnAllyBeforeSwitchOut { get; init; }
    public OnAllyTryBoostEventInfo? OnAllyTryBoost { get; init; }
    public OnAllyChargeMoveEventInfo? OnAllyChargeMove { get; init; }
    public OnAllyCriticalHitEventInfo? OnAllyCriticalHit { get; init; }
    public OnAllyDamageEventInfo? OnAllyDamage { get; init; }
    public OnAllyDeductPpEventInfo? OnAllyDeductPp { get; init; }
    public OnAllyDisableMoveEventInfo? OnAllyDisableMove { get; init; }
    public OnAllyDragOutEventInfo? OnAllyDragOut { get; init; }
    public OnAllyEatItemEventInfo? OnAllyEatItem { get; init; }
    public OnAllyEffectivenessEventInfo? OnAllyEffectiveness { get; init; }
    public OnAllyFaintEventInfo? OnAllyFaint { get; init; }
    public OnAllyFlinchEventInfo? OnAllyFlinch { get; init; }
    public OnAllyHitEventInfo? OnAllyHit { get; init; }
    public OnAllyImmunityEventInfo? OnAllyImmunity { get; init; }
    public OnAllyLockMoveEventInfo? OnAllyLockMove { get; init; }
    public OnAllyMaybeTrapPokemonEventInfo? OnAllyMaybeTrapPokemon { get; init; }
    public OnAllyModifyAccuracyEventInfo? OnAllyModifyAccuracy { get; init; }
    public OnAllyModifyAtkEventInfo? OnAllyModifyAtk { get; init; }
    public OnAllyModifyBoostEventInfo? OnAllyModifyBoost { get; init; }
    public OnAllyModifyCritRatioEventInfo? OnAllyModifyCritRatio { get; init; }
    public OnAllyModifyDamageEventInfo? OnAllyModifyDamage { get; init; }
    public OnAllyModifyDefEventInfo? OnAllyModifyDef { get; init; }
    public OnAllyModifyMoveEventInfo? OnAllyModifyMove { get; init; }
    public OnAllyModifyPriorityEventInfo? OnAllyModifyPriority { get; init; }
    public OnAllyModifySecondariesEventInfo? OnAllyModifySecondaries { get; init; }
    public OnAllyModifySpAEventInfo? OnAllyModifySpA { get; init; }
    public OnAllyModifySpDEventInfo? OnAllyModifySpD { get; init; }
    public OnAllyModifySpeEventInfo? OnAllyModifySpe { get; init; }
    public OnAllyModifyStabEventInfo? OnAllyModifyStab { get; init; }
    public OnAllyModifyTypeEventInfo? OnAllyModifyType { get; init; }
    public OnAllyModifyTargetEventInfo? OnAllyModifyTarget { get; init; }
    public OnAllyModifyWeightEventInfo? OnAllyModifyWeight { get; init; }
    public OnAllyMoveAbortedEventInfo? OnAllyMoveAborted { get; init; }
    public OnAllyNegateImmunityEventInfo? OnAllyNegateImmunity { get; init; }
    public OnAllyOverrideActionEventInfo? OnAllyOverrideAction { get; init; }
    public OnAllyPrepareHitEventInfo? OnAllyPrepareHit { get; init; }
    public OnAllyRedirectTargetEventInfo? OnAllyRedirectTarget { get; init; }
    public OnAllyResidualEventInfo? OnAllyResidual { get; init; }
    public OnAllySetAbilityEventInfo? OnAllySetAbility { get; init; }
    public OnAllySetStatusEventInfo? OnAllySetStatus { get; init; }
    public OnAllySetWeatherEventInfo? OnAllySetWeather { get; init; }
    public OnAllyStallMoveEventInfo? OnAllyStallMove { get; init; }
    public OnAllySwitchOutEventInfo? OnAllySwitchOut { get; init; }
    public OnAllyTakeItemEventInfo? OnAllyTakeItem { get; init; }
    public OnAllyTerrainEventInfo? OnAllyTerrain { get; init; }
    public OnAllyTrapPokemonEventInfo? OnAllyTrapPokemon { get; init; }
    public OnAllyTryAddVolatileEventInfo? OnAllyTryAddVolatile { get; init; }
    public OnAllyTryEatItemEventInfo? OnAllyTryEatItem { get; init; }
    public OnAllyTryHealEventInfo? OnAllyTryHeal { get; init; }
    public OnAllyTryHitEventInfo? OnAllyTryHit { get; init; }
    public OnAllyTryHitFieldEventInfo? OnAllyTryHitField { get; init; }
    public OnAllyTryHitSideEventInfo? OnAllyTryHitSide { get; init; }
    public OnAllyInvulnerabilityEventInfo? OnAllyInvulnerability { get; init; }
    public OnAllyTryMoveEventInfo? OnAllyTryMove { get; init; }
    public OnAllyTryPrimaryHitEventInfo? OnAllyTryPrimaryHit { get; init; }
    public OnAllyTypeEventInfo? OnAllyType { get; init; }
    public OnAllyWeatherModifyDamageEventInfo? OnAllyWeatherModifyDamage { get; init; }
    public OnAllyModifyDamagePhase1EventInfo? OnAllyModifyDamagePhase1 { get; init; }
    public OnAllyModifyDamagePhase2EventInfo? OnAllyModifyDamagePhase2 { get; init; }
}