namespace ApogeeVGC.Sim.Conditions;

public enum ConditionId
{
    Burn,
    Paralysis,
    Sleep,
    Freeze,
    Poison,
    Toxic,
    Confusion,
    Flinch,
    ChoiceLock,
    LeechSeed,
    TrickRoom,
    Stall,
    Protect,
    Tailwind,
    Reflect,
    LightScreen,
    ElectricTerrain,
    QuarkDrive,

    Nightmare,
    LockedMove,
    PartialTrappingLock,
    Yawn,
    GastroAcid,
    Commanding,
    Embargo,
    MagicRoom,
    WonderRoom,
    Gravity,
    Ingrain,
    SmackDown,
    Roost,
    MagnetRise,
    Telekinesis,
    SkyDrop,
    Fly,
    Bounce,
    Dive,
    Dig,
    PhantomForce,
    ShadowForce,
    RevivalBlessing,
    HealBlock,
    Trapped,
    Drain,
    Recoil,
    StruggleRecoil,
    PartiallyTrapped,
    Powder,
    Rest,
    Wish,
    TwoTurnMove,
    IceBall,
    Rollout,
    Fainted,
    SunnyDay,
    DesolateLand,
    PrimordialSea,
    RainDance,
    Substitute,
    ShedTail,
    DragonCheer,
    FocusEnergy,
    LaserFocus,
    Detect,
    MaxGuard,
    KingsShield,
    SpikyShield,
    BanefulBunker,
    Obstruct,
    SilkTrap,
    BurningBulwark,
    QuickGuard,
    WideGuard,
    Commanded,

    None,
}

//public enum ConditionEffectType
//{
//    Condition,
//    Weather,
//    Status,
//    Terrain,
//}