using ApogeeVGC.Sim.Events.Handlers.EventMethods;

namespace ApogeeVGC.Sim.Events;

/// <summary>
/// Modern interface for event methods using strongly-typed EventHandlerInfo records.
/// This replaces IEventMethods with a type-safe approach that validates delegate signatures at compile-time.
/// Each EventHandlerInfo record contains its own Priority, Order, and SubOrder properties.
/// </summary>
public interface IEventMethodsV2
{
    // Base Events (No Prefix)
    OnDamagingHitEventInfo? OnDamagingHit { get; }
    OnEmergencyExitEventInfo? OnEmergencyExit { get; }
    OnAfterEachBoostEventInfo? OnAfterEachBoost { get; }
    OnAfterHitEventInfo? OnAfterHit { get; }
    OnAfterMegaEventInfo? OnAfterMega { get; }
    OnAfterSetStatusEventInfo? OnAfterSetStatus { get; }
    OnAfterSubDamageEventInfo? OnAfterSubDamage { get; }
    OnAfterSwitchInSelfEventInfo? OnAfterSwitchInSelf { get; }
    OnAfterTerastallizationEventInfo? OnAfterTerastallization { get; }
    OnAfterUseItemEventInfo? OnAfterUseItem { get; }
    OnAfterTakeItemEventInfo? OnAfterTakeItem { get; }
    OnAfterBoostEventInfo? OnAfterBoost { get; }
    OnAfterFaintEventInfo? OnAfterFaint { get; }
    OnAfterMoveSecondarySelfEventInfo? OnAfterMoveSecondarySelf { get; }
    OnAfterMoveSecondaryEventInfo? OnAfterMoveSecondary { get; }
    OnAfterMoveEventInfo? OnAfterMove { get; }
    OnAfterMoveSelfEventInfo? OnAfterMoveSelf { get; }
    OnAttractEventInfo? OnAttract { get; }
    OnAccuracyEventInfo? OnAccuracy { get; }
    OnBasePowerEventInfo? OnBasePower { get; }
    OnBeforeFaintEventInfo? OnBeforeFaint { get; }
    OnBeforeMoveEventInfo? OnBeforeMove { get; }
    OnBeforeSwitchInEventInfo? OnBeforeSwitchIn { get; }
    OnBeforeSwitchOutEventInfo? OnBeforeSwitchOut { get; }
    OnBeforeTurnEventInfo? OnBeforeTurn { get; }
    OnChangeBoostEventInfo? OnChangeBoost { get; }
    OnTryBoostEventInfo? OnTryBoost { get; }
    OnChargeMoveEventInfo? OnChargeMove { get; }
    OnCriticalHitEventInfo? OnCriticalHit { get; }
    OnDamageEventInfo? OnDamage { get; }
    OnDeductPpEventInfo? OnDeductPp { get; }
    OnDisableMoveEventInfo? OnDisableMove { get; }
    OnDragOutEventInfo? OnDragOut { get; }
    OnEatItemEventInfo? OnEatItem { get; }
    OnEffectivenessEventInfo? OnEffectiveness { get; }
    OnEntryHazardEventInfo? OnEntryHazard { get; }
    OnFaintEventInfo? OnFaint { get; }
    OnFlinchEventInfo? OnFlinch { get; }
    OnFractionalPriorityEventInfo? OnFractionalPriority { get; }
    OnHitEventInfo? OnHit { get; }
    OnImmunityEventInfo? OnImmunity { get; }
    OnLockMoveEventInfo? OnLockMove { get; }
    OnMaybeTrapPokemonEventInfo? OnMaybeTrapPokemon { get; }
    OnModifyAccuracyEventInfo? OnModifyAccuracy { get; }
    OnModifyAtkEventInfo? OnModifyAtk { get; }
    OnModifyBoostEventInfo? OnModifyBoost { get; }
    OnModifyCritRatioEventInfo? OnModifyCritRatio { get; }
    OnModifyDamageEventInfo? OnModifyDamage { get; }
    OnModifyDefEventInfo? OnModifyDef { get; }
    OnModifyMoveEventInfo? OnModifyMove { get; }
    OnModifyPriorityEventInfo? OnModifyPriority { get; }
    OnModifySecondariesEventInfo? OnModifySecondaries { get; }
    OnModifyTypeEventInfo? OnModifyType { get; }
    OnModifyTargetEventInfo? OnModifyTarget { get; }
    OnModifySpAEventInfo? OnModifySpA { get; }
    OnModifySpDEventInfo? OnModifySpD { get; }
    OnModifySpeEventInfo? OnModifySpe { get; }
    OnModifyStabEventInfo? OnModifyStab { get; }
    OnModifyWeightEventInfo? OnModifyWeight { get; }
    OnMoveAbortedEventInfo? OnMoveAborted { get; }
    OnNegateImmunityEventInfo? OnNegateImmunity { get; }
    OnOverrideActionEventInfo? OnOverrideAction { get; }
    OnPrepareHitEventInfo? OnPrepareHit { get; }
    OnPseudoWeatherChangeEventInfo? OnPseudoWeatherChange { get; }
    OnRedirectTargetEventInfo? OnRedirectTarget { get; }
    OnResidualEventInfo? OnResidual { get; }
    OnSetAbilityEventInfo? OnSetAbility { get; }
    OnSetStatusEventInfo? OnSetStatus { get; }
    OnSetWeatherEventInfo? OnSetWeather { get; }
    OnSideConditionStartEventInfo? OnSideConditionStart { get; }
    OnStallMoveEventInfo? OnStallMove { get; }
    OnSwitchInEventInfo? OnSwitchIn { get; }
    OnSwitchOutEventInfo? OnSwitchOut { get; }
    OnSwapEventInfo? OnSwap { get; }
    OnTakeItemEventInfo? OnTakeItem { get; }
    OnWeatherChangeEventInfo? OnWeatherChange { get; }
    OnTerrainChangeEventInfo? OnTerrainChange { get; }
    OnTrapPokemonEventInfo? OnTrapPokemon { get; }
    OnTryAddVolatileEventInfo? OnTryAddVolatile { get; }
    OnTryEatItemEventInfo? OnTryEatItem { get; }
    OnTryHealEventInfo? OnTryHeal { get; }
    OnTryHitEventInfo? OnTryHit { get; }
    OnTryHitFieldEventInfo? OnTryHitField { get; }
    OnTryHitSideEventInfo? OnTryHitSide { get; }
    OnInvulnerabilityEventInfo? OnInvulnerability { get; }
    OnTryMoveEventInfo? OnTryMove { get; }
    OnTryPrimaryHitEventInfo? OnTryPrimaryHit { get; }
    OnTypeEventInfo? OnType { get; }
    OnUseItemEventInfo? OnUseItem { get; }
    OnUpdateEventInfo? OnUpdate { get; }
    OnWeatherEventInfo? OnWeather { get; }
    OnWeatherModifyDamageEventInfo? OnWeatherModifyDamage { get; }
    OnModifyDamagePhase1EventInfo? OnModifyDamagePhase1 { get; }
    OnModifyDamagePhase2EventInfo? OnModifyDamagePhase2 { get; }

    // Foe Prefix Events
    OnFoeDamagingHitEventInfo? OnFoeDamagingHit { get; }
    OnFoeAfterEachBoostEventInfo? OnFoeAfterEachBoost { get; }
    OnFoeAfterHitEventInfo? OnFoeAfterHit { get; }
    OnFoeAfterSetStatusEventInfo? OnFoeAfterSetStatus { get; }
    OnFoeAfterSubDamageEventInfo? OnFoeAfterSubDamage { get; }
    OnFoeAfterSwitchInSelfEventInfo? OnFoeAfterSwitchInSelf { get; }
    OnFoeAfterUseItemEventInfo? OnFoeAfterUseItem { get; }
    OnFoeAfterBoostEventInfo? OnFoeAfterBoost { get; }
    OnFoeAfterFaintEventInfo? OnFoeAfterFaint { get; }
    OnFoeAfterMoveSecondarySelfEventInfo? OnFoeAfterMoveSecondarySelf { get; }
    OnFoeAfterMoveSecondaryEventInfo? OnFoeAfterMoveSecondary { get; }
    OnFoeAfterMoveEventInfo? OnFoeAfterMove { get; }
    OnFoeAfterMoveSelfEventInfo? OnFoeAfterMoveSelf { get; }
    OnFoeAttractEventInfo? OnFoeAttract { get; }
    OnFoeAccuracyEventInfo? OnFoeAccuracy { get; }
    OnFoeBasePowerEventInfo? OnFoeBasePower { get; }
    OnFoeBeforeFaintEventInfo? OnFoeBeforeFaint { get; }
    OnFoeBeforeMoveEventInfo? OnFoeBeforeMove { get; }
    OnFoeBeforeSwitchInEventInfo? OnFoeBeforeSwitchIn { get; }
    OnFoeBeforeSwitchOutEventInfo? OnFoeBeforeSwitchOut { get; }
    OnFoeTryBoostEventInfo? OnFoeTryBoost { get; }
    OnFoeChargeMoveEventInfo? OnFoeChargeMove { get; }
    OnFoeCriticalHitEventInfo? OnFoeCriticalHit { get; }
    OnFoeDamageEventInfo? OnFoeDamage { get; }
    OnFoeDeductPpEventInfo? OnFoeDeductPp { get; }
    OnFoeDisableMoveEventInfo? OnFoeDisableMove { get; }
    OnFoeDragOutEventInfo? OnFoeDragOut { get; }
    OnFoeEatItemEventInfo? OnFoeEatItem { get; }
    OnFoeEffectivenessEventInfo? OnFoeEffectiveness { get; }
    OnFoeFaintEventInfo? OnFoeFaint { get; }
    OnFoeFlinchEventInfo? OnFoeFlinch { get; }
    OnFoeHitEventInfo? OnFoeHit { get; }
    OnFoeImmunityEventInfo? OnFoeImmunity { get; }
    OnFoeLockMoveEventInfo? OnFoeLockMove { get; }
    OnFoeMaybeTrapPokemonEventInfo? OnFoeMaybeTrapPokemon { get; }
    OnFoeModifyAccuracyEventInfo? OnFoeModifyAccuracy { get; }
    OnFoeModifyAtkEventInfo? OnFoeModifyAtk { get; }
    OnFoeModifyBoostEventInfo? OnFoeModifyBoost { get; }
    OnFoeModifyCritRatioEventInfo? OnFoeModifyCritRatio { get; }
    OnFoeModifyDamageEventInfo? OnFoeModifyDamage { get; }
    OnFoeModifyDefEventInfo? OnFoeModifyDef { get; }
    OnFoeModifyMoveEventInfo? OnFoeModifyMove { get; }
    OnFoeModifyPriorityEventInfo? OnFoeModifyPriority { get; }
    OnFoeModifySecondariesEventInfo? OnFoeModifySecondaries { get; }
    OnFoeModifySpAEventInfo? OnFoeModifySpA { get; }
    OnFoeModifySpDEventInfo? OnFoeModifySpD { get; }
    OnFoeModifySpeEventInfo? OnFoeModifySpe { get; }
    OnFoeModifyStabEventInfo? OnFoeModifyStab { get; }
    OnFoeModifyTypeEventInfo? OnFoeModifyType { get; }
    OnFoeModifyTargetEventInfo? OnFoeModifyTarget { get; }
    OnFoeModifyWeightEventInfo? OnFoeModifyWeight { get; }
    OnFoeMoveAbortedEventInfo? OnFoeMoveAborted { get; }
    OnFoeNegateImmunityEventInfo? OnFoeNegateImmunity { get; }
    OnFoeOverrideActionEventInfo? OnFoeOverrideAction { get; }
    OnFoePrepareHitEventInfo? OnFoePrepareHit { get; }
    OnFoeRedirectTargetEventInfo? OnFoeRedirectTarget { get; }
    OnFoeResidualEventInfo? OnFoeResidual { get; }
    OnFoeSetAbilityEventInfo? OnFoeSetAbility { get; }
    OnFoeSetStatusEventInfo? OnFoeSetStatus { get; }
    OnFoeSetWeatherEventInfo? OnFoeSetWeather { get; }
    OnFoeStallMoveEventInfo? OnFoeStallMove { get; }
    OnFoeSwitchOutEventInfo? OnFoeSwitchOut { get; }
    OnFoeTakeItemEventInfo? OnFoeTakeItem { get; }
    OnFoeTerrainEventInfo? OnFoeTerrain { get; }
    OnFoeTrapPokemonEventInfo? OnFoeTrapPokemon { get; }
    OnFoeTryAddVolatileEventInfo? OnFoeTryAddVolatile { get; }
    OnFoeTryEatItemEventInfo? OnFoeTryEatItem { get; }
    OnFoeTryHealEventInfo? OnFoeTryHeal { get; }
    OnFoeTryHitEventInfo? OnFoeTryHit { get; }
    OnFoeTryHitFieldEventInfo? OnFoeTryHitField { get; }
    OnFoeTryHitSideEventInfo? OnFoeTryHitSide { get; }
    OnFoeInvulnerabilityEventInfo? OnFoeInvulnerability { get; }
    OnFoeTryMoveEventInfo? OnFoeTryMove { get; }
    OnFoeTryPrimaryHitEventInfo? OnFoeTryPrimaryHit { get; }
    OnFoeTypeEventInfo? OnFoeType { get; }
    OnFoeWeatherModifyDamageEventInfo? OnFoeWeatherModifyDamage { get; }
    OnFoeModifyDamagePhase1EventInfo? OnFoeModifyDamagePhase1 { get; }
    OnFoeModifyDamagePhase2EventInfo? OnFoeModifyDamagePhase2 { get; }

    // Source Prefix Events
    OnSourceDamagingHitEventInfo? OnSourceDamagingHit { get; }
    OnSourceAfterEachBoostEventInfo? OnSourceAfterEachBoost { get; }
    OnSourceAfterHitEventInfo? OnSourceAfterHit { get; }
    OnSourceAfterSetStatusEventInfo? OnSourceAfterSetStatus { get; }
    OnSourceAfterSubDamageEventInfo? OnSourceAfterSubDamage { get; }
    OnSourceAfterSwitchInSelfEventInfo? OnSourceAfterSwitchInSelf { get; }
    OnSourceAfterUseItemEventInfo? OnSourceAfterUseItem { get; }
    OnSourceAfterBoostEventInfo? OnSourceAfterBoost { get; }
    OnSourceAfterFaintEventInfo? OnSourceAfterFaint { get; }
    OnSourceAfterMoveSecondarySelfEventInfo? OnSourceAfterMoveSecondarySelf { get; }
    OnSourceAfterMoveSecondaryEventInfo? OnSourceAfterMoveSecondary { get; }
    OnSourceAfterMoveEventInfo? OnSourceAfterMove { get; }
    OnSourceAfterMoveSelfEventInfo? OnSourceAfterMoveSelf { get; }
    OnSourceAttractEventInfo? OnSourceAttract { get; }
    OnSourceAccuracyEventInfo? OnSourceAccuracy { get; }
    OnSourceBasePowerEventInfo? OnSourceBasePower { get; }
    OnSourceBeforeFaintEventInfo? OnSourceBeforeFaint { get; }
    OnSourceBeforeMoveEventInfo? OnSourceBeforeMove { get; }
    OnSourceBeforeSwitchInEventInfo? OnSourceBeforeSwitchIn { get; }
    OnSourceBeforeSwitchOutEventInfo? OnSourceBeforeSwitchOut { get; }
    OnSourceTryBoostEventInfo? OnSourceTryBoost { get; }
    OnSourceChargeMoveEventInfo? OnSourceChargeMove { get; }
    OnSourceCriticalHitEventInfo? OnSourceCriticalHit { get; }
    OnSourceDamageEventInfo? OnSourceDamage { get; }
    OnSourceDeductPpEventInfo? OnSourceDeductPp { get; }
    OnSourceDisableMoveEventInfo? OnSourceDisableMove { get; }
    OnSourceDragOutEventInfo? OnSourceDragOut { get; }
    OnSourceEatItemEventInfo? OnSourceEatItem { get; }
    OnSourceEffectivenessEventInfo? OnSourceEffectiveness { get; }
    OnSourceFaintEventInfo? OnSourceFaint { get; }
    OnSourceFlinchEventInfo? OnSourceFlinch { get; }
    OnSourceHitEventInfo? OnSourceHit { get; }
    OnSourceImmunityEventInfo? OnSourceImmunity { get; }
    OnSourceLockMoveEventInfo? OnSourceLockMove { get; }
    OnSourceMaybeTrapPokemonEventInfo? OnSourceMaybeTrapPokemon { get; }
    OnSourceModifyAccuracyEventInfo? OnSourceModifyAccuracy { get; }
    OnSourceModifyAtkEventInfo? OnSourceModifyAtk { get; }
    OnSourceModifyBoostEventInfo? OnSourceModifyBoost { get; }
    OnSourceModifyCritRatioEventInfo? OnSourceModifyCritRatio { get; }
    OnSourceModifyDamageEventInfo? OnSourceModifyDamage { get; }
    OnSourceModifyDefEventInfo? OnSourceModifyDef { get; }
    OnSourceModifyMoveEventInfo? OnSourceModifyMove { get; }
    OnSourceModifyPriorityEventInfo? OnSourceModifyPriority { get; }
    OnSourceModifySecondariesEventInfo? OnSourceModifySecondaries { get; }
    OnSourceModifySpAEventInfo? OnSourceModifySpA { get; }
    OnSourceModifySpDEventInfo? OnSourceModifySpD { get; }
    OnSourceModifySpeEventInfo? OnSourceModifySpe { get; }
    OnSourceModifyStabEventInfo? OnSourceModifyStab { get; }
    OnSourceModifyTypeEventInfo? OnSourceModifyType { get; }
    OnSourceModifyTargetEventInfo? OnSourceModifyTarget { get; }
    OnSourceModifyWeightEventInfo? OnSourceModifyWeight { get; }
    OnSourceMoveAbortedEventInfo? OnSourceMoveAborted { get; }
    OnSourceNegateImmunityEventInfo? OnSourceNegateImmunity { get; }
    OnSourceOverrideActionEventInfo? OnSourceOverrideAction { get; }
    OnSourcePrepareHitEventInfo? OnSourcePrepareHit { get; }
    OnSourceRedirectTargetEventInfo? OnSourceRedirectTarget { get; }
    OnSourceResidualEventInfo? OnSourceResidual { get; }
    OnSourceSetAbilityEventInfo? OnSourceSetAbility { get; }
    OnSourceSetStatusEventInfo? OnSourceSetStatus { get; }
    OnSourceSetWeatherEventInfo? OnSourceSetWeather { get; }
    OnSourceStallMoveEventInfo? OnSourceStallMove { get; }
    OnSourceSwitchOutEventInfo? OnSourceSwitchOut { get; }
    OnSourceTakeItemEventInfo? OnSourceTakeItem { get; }
    OnSourceTerrainEventInfo? OnSourceTerrain { get; }
    OnSourceTrapPokemonEventInfo? OnSourceTrapPokemon { get; }
    OnSourceTryAddVolatileEventInfo? OnSourceTryAddVolatile { get; }
    OnSourceTryEatItemEventInfo? OnSourceTryEatItem { get; }
    OnSourceTryHealEventInfo? OnSourceTryHeal { get; }
    OnSourceTryHitEventInfo? OnSourceTryHit { get; }
    OnSourceTryHitFieldEventInfo? OnSourceTryHitField { get; }
    OnSourceTryHitSideEventInfo? OnSourceTryHitSide { get; }
    OnSourceInvulnerabilityEventInfo? OnSourceInvulnerability { get; }
    OnSourceTryMoveEventInfo? OnSourceTryMove { get; }
    OnSourceTryPrimaryHitEventInfo? OnSourceTryPrimaryHit { get; }
    OnSourceTypeEventInfo? OnSourceType { get; }
    OnSourceWeatherModifyDamageEventInfo? OnSourceWeatherModifyDamage { get; }
    OnSourceModifyDamagePhase1EventInfo? OnSourceModifyDamagePhase1 { get; }
    OnSourceModifyDamagePhase2EventInfo? OnSourceModifyDamagePhase2 { get; }

    // Any Prefix Events
    OnAnyDamagingHitEventInfo? OnAnyDamagingHit { get; }
    OnAnyAfterEachBoostEventInfo? OnAnyAfterEachBoost { get; }
    OnAnyAfterHitEventInfo? OnAnyAfterHit { get; }
    OnAnyAfterSetStatusEventInfo? OnAnyAfterSetStatus { get; }
    OnAnyAfterSubDamageEventInfo? OnAnyAfterSubDamage { get; }
    OnAnyAfterSwitchInSelfEventInfo? OnAnyAfterSwitchInSelf { get; }
    OnAnyAfterUseItemEventInfo? OnAnyAfterUseItem { get; }
    OnAnyAfterBoostEventInfo? OnAnyAfterBoost { get; }
    OnAnyAfterFaintEventInfo? OnAnyAfterFaint { get; }
    OnAnyAfterMegaEventInfo? OnAnyAfterMega { get; }
    OnAnyAfterMoveSecondarySelfEventInfo? OnAnyAfterMoveSecondarySelf { get; }
    OnAnyAfterMoveSecondaryEventInfo? OnAnyAfterMoveSecondary { get; }
    OnAnyAfterMoveEventInfo? OnAnyAfterMove { get; }
    OnAnyAfterMoveSelfEventInfo? OnAnyAfterMoveSelf { get; }
    OnAnyAfterTerastallizationEventInfo? OnAnyAfterTerastallization { get; }
    OnAnyAttractEventInfo? OnAnyAttract { get; }
    OnAnyAccuracyEventInfo? OnAnyAccuracy { get; }
    OnAnyBasePowerEventInfo? OnAnyBasePower { get; }
    OnAnyBeforeFaintEventInfo? OnAnyBeforeFaint { get; }
    OnAnyBeforeMoveEventInfo? OnAnyBeforeMove { get; }
    OnAnyBeforeSwitchInEventInfo? OnAnyBeforeSwitchIn { get; }
    OnAnyBeforeSwitchOutEventInfo? OnAnyBeforeSwitchOut { get; }
    OnAnyTryBoostEventInfo? OnAnyTryBoost { get; }
    OnAnyChargeMoveEventInfo? OnAnyChargeMove { get; }
    OnAnyCriticalHitEventInfo? OnAnyCriticalHit { get; }
    OnAnyDamageEventInfo? OnAnyDamage { get; }
    OnAnyDeductPpEventInfo? OnAnyDeductPp { get; }
    OnAnyDisableMoveEventInfo? OnAnyDisableMove { get; }
    OnAnyDragOutEventInfo? OnAnyDragOut { get; }
    OnAnyEatItemEventInfo? OnAnyEatItem { get; }
    OnAnyEffectivenessEventInfo? OnAnyEffectiveness { get; }
    OnAnyFaintEventInfo? OnAnyFaint { get; }
    OnAnyFlinchEventInfo? OnAnyFlinch { get; }
    OnAnyHitEventInfo? OnAnyHit { get; }
    OnAnyImmunityEventInfo? OnAnyImmunity { get; }
    OnAnyLockMoveEventInfo? OnAnyLockMove { get; }
    OnAnyMaybeTrapPokemonEventInfo? OnAnyMaybeTrapPokemon { get; }
    OnAnyModifyAccuracyEventInfo? OnAnyModifyAccuracy { get; }
    OnAnyModifyAtkEventInfo? OnAnyModifyAtk { get; }
    OnAnyModifyBoostEventInfo? OnAnyModifyBoost { get; }
    OnAnyModifyCritRatioEventInfo? OnAnyModifyCritRatio { get; }
    OnAnyModifyDamageEventInfo? OnAnyModifyDamage { get; }
    OnAnyModifyDefEventInfo? OnAnyModifyDef { get; }
    OnAnyModifyMoveEventInfo? OnAnyModifyMove { get; }
    OnAnyModifyPriorityEventInfo? OnAnyModifyPriority { get; }
    OnAnyModifySecondariesEventInfo? OnAnyModifySecondaries { get; }
    OnAnyModifySpAEventInfo? OnAnyModifySpA { get; }
    OnAnyModifySpDEventInfo? OnAnyModifySpD { get; }
    OnAnyModifySpeEventInfo? OnAnyModifySpe { get; }
    OnAnyModifyStabEventInfo? OnAnyModifyStab { get; }
    OnAnyModifyTypeEventInfo? OnAnyModifyType { get; }
    OnAnyModifyTargetEventInfo? OnAnyModifyTarget { get; }
    OnAnyModifyWeightEventInfo? OnAnyModifyWeight { get; }
    OnAnyMoveAbortedEventInfo? OnAnyMoveAborted { get; }
    OnAnyNegateImmunityEventInfo? OnAnyNegateImmunity { get; }
    OnAnyOverrideActionEventInfo? OnAnyOverrideAction { get; }
    OnAnyPrepareHitEventInfo? OnAnyPrepareHit { get; }
    OnAnyPseudoWeatherChangeEventInfo? OnAnyPseudoWeatherChange { get; }
    OnAnyRedirectTargetEventInfo? OnAnyRedirectTarget { get; }
    OnAnyResidualEventInfo? OnAnyResidual { get; }
    OnAnySetAbilityEventInfo? OnAnySetAbility { get; }
    OnAnySetStatusEventInfo? OnAnySetStatus { get; }
    OnAnySetWeatherEventInfo? OnAnySetWeather { get; }
    OnAnyStallMoveEventInfo? OnAnyStallMove { get; }
    OnAnySwitchInEventInfo? OnAnySwitchIn { get; }
    OnAnySwitchOutEventInfo? OnAnySwitchOut { get; }
    OnAnyTakeItemEventInfo? OnAnyTakeItem { get; }
    OnAnyTerrainEventInfo? OnAnyTerrain { get; }
    OnAnyTrapPokemonEventInfo? OnAnyTrapPokemon { get; }
    OnAnyTryAddVolatileEventInfo? OnAnyTryAddVolatile { get; }
    OnAnyTryEatItemEventInfo? OnAnyTryEatItem { get; }
    OnAnyTryHealEventInfo? OnAnyTryHeal { get; }
    OnAnyTryHitEventInfo? OnAnyTryHit { get; }
    OnAnyTryHitFieldEventInfo? OnAnyTryHitField { get; }
    OnAnyTryHitSideEventInfo? OnAnyTryHitSide { get; }
    OnAnyInvulnerabilityEventInfo? OnAnyInvulnerability { get; }
    OnAnyTryMoveEventInfo? OnAnyTryMove { get; }
    OnAnyTryPrimaryHitEventInfo? OnAnyTryPrimaryHit { get; }
    OnAnyTypeEventInfo? OnAnyType { get; }
    OnAnyWeatherModifyDamageEventInfo? OnAnyWeatherModifyDamage { get; }
    OnAnyModifyDamagePhase1EventInfo? OnAnyModifyDamagePhase1 { get; }
    OnAnyModifyDamagePhase2EventInfo? OnAnyModifyDamagePhase2 { get; }

    // Ally Prefix Events
    OnAllyBasePowerEventInfo? OnAllyBasePower { get; }
    OnAllyModifyAtkEventInfo? OnAllyModifyAtk { get; }
    OnAllyModifySpAEventInfo? OnAllyModifySpA { get; }
    OnAllyModifySpDEventInfo? OnAllyModifySpD { get; }
    OnAllyTryHitSideEventInfo? OnAllyTryHitSide { get; }
    OnAllyDamagingHitEventInfo? OnAllyDamagingHit { get; }
    OnAllyAfterHitEventInfo? OnAllyAfterHit { get; }
    OnAllyAfterSetStatusEventInfo? OnAllyAfterSetStatus { get; }
    OnAllyModifyAccuracyEventInfo? OnAllyModifyAccuracy { get; }
    OnAllyTryHitEventInfo? OnAllyTryHit { get; }
    OnAllyInvulnerabilityEventInfo? OnAllyInvulnerability { get; }
    OnAllySwitchOutEventInfo? OnAllySwitchOut { get; }
    OnAllyFaintEventInfo? OnAllyFaint { get; }
    OnAllyAfterBoostEventInfo? OnAllyAfterBoost { get; }
    OnAllyPrepareHitEventInfo? OnAllyPrepareHit { get; }
}
