"""
Parser equivalence tests — validates the Python parser against C# ground truth.

Reads fixtures from test_fixtures/parser_fixtures.json (generated by
ApogeeVGC.Tests.ParserEquivalenceTests) and compares the parser's output
at each turn against the C# BattlePerspective snapshot.

Run: python test_parser_equivalence.py
Generate fixtures first: dotnet test --filter GenerateParserFixtures
"""

import json
import sys
import unittest
from pathlib import Path

from parser import parse_replay

FIXTURE_PATH = Path(__file__).parent / "test_fixtures" / "parser_fixtures.json"

# Map C# ConditionId.ToString() to parser volatile names
VOLATILE_MAP = {
    "Substitute": "substitute",
    "Confusion": "confusion",
    "Taunt": "taunt",
    "Encore": "encore",
    "Disable": "disable",
    "Yawn": "yawn",
    "LeechSeed": "leech_seed",
    "PerishSong": "perish_song",
    "Protect": "protected",
    "Torment": "torment",
    "Imprison": "imprison",
}

# Volatiles the parser tracks
TRACKED_VOLATILES = set(VOLATILE_MAP.values())


def load_fixtures():
    if not FIXTURE_PATH.exists():
        print(f"Fixtures not found at {FIXTURE_PATH}")
        print("Generate them first: dotnet test --filter GenerateParserFixtures")
        sys.exit(1)
    with open(FIXTURE_PATH, encoding="utf-8") as f:
        return json.load(f)


def build_fake_replay(fixture):
    """Build a fake replay dict that the parser can process from the C# log lines.

    Injects |player| lines that the C# protocol doesn't emit but the parser
    requires to map winner names to side IDs.
    """
    # Inject player metadata lines at the start (before |gen|)
    player_lines = [
        "|player|p1|Player 1|",
        "|player|p2|Player 2|",
    ]
    log_text = "\n".join(player_lines + fixture["log"])
    return {"log": log_text}


def compare_active(parser_active, csharp_active, slot_label, errors):
    """Compare a single active pokemon's state between parser and C# ground truth."""
    if csharp_active is None:
        if parser_active is not None:
            errors.append(f"{slot_label}: parser has pokemon but C# slot is empty")
        return
    if parser_active is None:
        errors.append(f"{slot_label}: C# has {csharp_active['species']} but parser slot is empty")
        return

    cs = csharp_active
    ps = parser_active

    # Species
    if ps["species"] != cs["species"]:
        errors.append(f"{slot_label}: species mismatch: parser={ps['species']} C#={cs['species']}")

    # HP — parser stores raw value from log (e.g. 133/155), C# stores percentage.
    # Showdown protocol HP is always current/max, so compute percentage.
    parser_hp_raw = ps.get("hp", 0)
    parser_max_hp = ps.get("max_hp", 100) or 100
    parser_hp_pct = int(round(100.0 * parser_hp_raw / parser_max_hp)) if parser_max_hp > 0 else 0
    if abs(parser_hp_pct - cs["hp"]) > 1:
        errors.append(f"{slot_label} ({cs['species']}): HP mismatch: parser={parser_hp_pct}% ({parser_hp_raw}/{parser_max_hp}) C#={cs['hp']}%")

    # Fainted
    parser_fainted = ps.get("fainted", False) or ps.get("hp", 100) == 0
    if parser_fainted != cs["fainted"]:
        errors.append(f"{slot_label} ({cs['species']}): fainted mismatch: parser={parser_fainted} C#={cs['fainted']}")

    # Status
    if ps.get("status") != cs["status"]:
        errors.append(f"{slot_label} ({cs['species']}): status mismatch: parser={ps.get('status')} C#={cs['status']}")

    # Boosts
    cs_boosts = cs["boosts"]
    ps_boosts = ps.get("boosts", {})
    for stat, cs_key in [("atk", "atk"), ("def", "def_"), ("spa", "spa"), ("spd", "spd"), ("spe", "spe")]:
        pv = ps_boosts.get(stat, 0)
        cv = cs_boosts.get(cs_key, 0)
        if pv != cv:
            errors.append(f"{slot_label} ({cs['species']}): {stat} boost mismatch: parser={pv} C#={cv}")

    # Volatiles (only check the ones the parser tracks)
    cs_volatiles = set()
    for v in cs["volatiles"]:
        mapped = VOLATILE_MAP.get(v)
        if mapped:
            cs_volatiles.add(mapped)
    ps_volatiles = set(ps.get("volatiles", [])) & TRACKED_VOLATILES

    if ps_volatiles != cs_volatiles:
        missing = cs_volatiles - ps_volatiles
        extra = ps_volatiles - cs_volatiles
        if missing:
            errors.append(f"{slot_label} ({cs['species']}): parser missing volatiles: {missing}")
        if extra:
            errors.append(f"{slot_label} ({cs['species']}): parser has extra volatiles: {extra}")


def compare_field(parser_field, csharp_field, perspective, errors):
    """Compare field state between parser and C# ground truth."""
    pf = parser_field or {}
    cf = csharp_field

    # Weather
    pw = pf.get("weather")
    cw = cf["weather"]
    if pw != cw:
        errors.append(f"weather mismatch: parser={pw} C#={cw}")

    # Terrain
    pt = pf.get("terrain")
    ct = cf["terrain"]
    if pt != ct:
        errors.append(f"terrain mismatch: parser={pt} C#={ct}")

    # Trick room
    ptr = pf.get("trick_room", False)
    ctr = cf["trick_room"]
    if ptr != ctr:
        errors.append(f"trick_room mismatch: parser={ptr} C#={ctr}")

    # Side conditions
    side = perspective  # "p1" or "p2"
    opp = "p2" if side == "p1" else "p1"

    for cond, cs_my_key, cs_opp_key, ps_my_key, ps_opp_key in [
        ("tailwind", "my_tailwind", "opp_tailwind",
         f"{side}_tailwind", f"{opp}_tailwind"),
        ("reflect", "my_reflect", "opp_reflect",
         f"{side}_reflect", f"{opp}_reflect"),
        ("light_screen", "my_light_screen", "opp_light_screen",
         f"{side}_light_screen", f"{opp}_light_screen"),
        ("aurora_veil", "my_aurora_veil", "opp_aurora_veil",
         f"{side}_aurora_veil", f"{opp}_aurora_veil"),
    ]:
        pmy = pf.get(ps_my_key, False)
        cmy = cf[cs_my_key]
        if pmy != cmy:
            errors.append(f"{cond} (my) mismatch: parser={pmy} C#={cmy}")
        popp = pf.get(ps_opp_key, False)
        copp = cf[cs_opp_key]
        if popp != copp:
            errors.append(f"{cond} (opp) mismatch: parser={popp} C#={copp}")


class TestParserEquivalence(unittest.TestCase):
    """Validate parser output against C# BattlePerspective ground truth."""

    @classmethod
    def setUpClass(cls):
        cls.fixtures = load_fixtures()

    def test_all_fixtures(self):
        """Run parser on all fixtures and compare against C# ground truth."""
        total_turns = 0
        total_errors = 0
        failed_fixtures = []

        for fixture in self.fixtures:
            idx = fixture["index"]
            replay = build_fake_replay(fixture)
            result = parse_replay(replay)

            if result is None:
                failed_fixtures.append((idx, ["parse_replay returned None"]))
                continue

            # Get parser decision points (turn_start only for comparison)
            decision_points = result.get("decision_points", result.get("turns", []))
            turn_starts = [dp for dp in decision_points if dp.get("type") == "turn_start"]

            # Build turn → decision point map
            parser_by_turn = {dp["turn"]: dp for dp in turn_starts}

            fixture_errors = []
            for cs_turn in fixture["turns"]:
                turn_num = cs_turn["turn"]
                total_turns += 1

                dp = parser_by_turn.get(turn_num)
                if dp is None:
                    fixture_errors.append(f"Turn {turn_num}: parser has no turn_start decision point")
                    continue

                # Compare both perspectives
                for perspective in ["p1", "p2"]:
                    cs_persp = cs_turn[perspective]
                    parser_active = dp.get("active", {})

                    # Compare own active pokemon
                    slot_letters = ["a", "b"]
                    for si, letter in enumerate(slot_letters):
                        slot_key = f"{perspective}{letter}"
                        p_active = parser_active.get(slot_key)
                        cs_own = cs_persp["active"][si] if si < len(cs_persp["active"]) else None

                        turn_errors = []
                        compare_active(p_active, cs_own, f"T{turn_num} {slot_key}", turn_errors)
                        fixture_errors.extend(turn_errors)

                    # Compare opponent active pokemon
                    opp = "p2" if perspective == "p1" else "p1"
                    for si, letter in enumerate(slot_letters):
                        slot_key = f"{opp}{letter}"
                        p_active = parser_active.get(slot_key)
                        cs_opp = cs_persp["opponent_active"][si] if si < len(cs_persp["opponent_active"]) else None

                        turn_errors = []
                        compare_active(p_active, cs_opp, f"T{turn_num} {slot_key}", turn_errors)
                        fixture_errors.extend(turn_errors)

                    # Compare field (from p1 perspective since field is shared)
                    if perspective == "p1":
                        turn_errors = []
                        compare_field(dp.get("field", {}), cs_persp["field"], perspective, turn_errors)
                        fixture_errors.extend(turn_errors)

            if fixture_errors:
                total_errors += len(fixture_errors)
                failed_fixtures.append((idx, fixture_errors))

        # Report results
        print(f"\n{'='*60}")
        print(f"Parser Equivalence Results:")
        print(f"  Fixtures: {len(self.fixtures)}")
        print(f"  Total turns compared: {total_turns}")
        print(f"  Total mismatches: {total_errors}")
        print(f"  Fixtures with errors: {len(failed_fixtures)}/{len(self.fixtures)}")

        if failed_fixtures:
            print(f"\nFirst 5 fixture errors:")
            for idx, errs in failed_fixtures[:5]:
                print(f"\n  Fixture {idx} ({len(errs)} errors):")
                for e in errs[:10]:
                    print(f"    - {e}")
                if len(errs) > 10:
                    print(f"    ... and {len(errs) - 10} more")

        # Each turn has ~8 pokemon comparisons (4 active × 2 perspectives)
        # plus field comparisons, so total checks ≈ turns × 10
        total_checks = total_turns * 10
        error_rate = total_errors / max(total_checks, 1)
        print(f"\n  Error rate: {error_rate:.4%} ({total_errors}/{total_checks} checks)")
        print(f"{'='*60}\n")

        # Fail if error rate exceeds 10% — allows known edge cases:
        # - Intimidate/ability boosts on switch (timing difference)
        # - Illusion disguise (parser sees disguise, C# sees real pokemon)
        # - Status timing (cured between snapshot points)
        self.assertLess(error_rate, 0.10,
                        f"Parser error rate {error_rate:.2%} exceeds 10% threshold")


if __name__ == "__main__":
    unittest.main()
