namespace ApogeeVGC.Sim.Items;

public enum ItemId
{
    ChoiceSpecs,
    FlameOrb,
    RockyHelmet,
    AssaultVest,
    AbilityShield,
    AbsorbBulb,
    AdamantCrystal,
    AdamantOrb,
    AdrenalineOrb,
    AguavBerry,
    AirBalloon,
    ApicotBerry,
    AspearBerry,
    AuspiciousArmor,

    // B items
    BabiriBerry,
    BeastBall,
    BerrySweet,
    BigNugget,
    BigRoot,
    BindingBand,
    BlackBelt,
    BlackGlasses,
    BlackSludge,
    BottleCap,
    BrightPowder,

    // C items
    CellBattery,
    Charcoal,
    ChartiBerry,
    CheriBerry,
    ChestoBerry,
    ChilanBerry,
    ChoiceBand,
    ChoiceScarf,
    ChopleBerry,
    ClearAmulet,
    CobaBerry,
    ColburBerry,
    CornerstoneMask,
    CovertCloak,
    CrackedPot,
    CustapBerry,

    // D items
    DampRock,
    DawnStone,
    DeepSeaScale,
    DeepSeaTooth,
    DestinyKnot,
    DiveBall,
    DracoPlate,
    DragonFang,
    DragonScale,
    DreadPlate,
    DreamBall,
    DubiousDisc,
    DuskBall,
    DuskStone,

    // E items
    EarthPlate,
    EjectButton,
    EjectPack,
    Electirizer,
    ElectricSeed,
    Eviolite,
    ExpertBelt,

    // F items
    FairyFeather,
    FastBall,
    FireStone,
    FistPlate,
    FlamePlate,
    FloatStone,
    FlowerSweet,
    FocusBand,
    FocusSash,
    FriendBall,

    // G items
    GalaricaCuff,
    GalaricaWreath,
    GanlonBerry,
    GoldBottleCap,
    GrassySeed,
    GreatBall,
    GrepaBerry,
    GripClaw,
    GriseousCore,
    GriseousOrb,

    // H items
    HabanBerry,
    HardStone,
    HealBall,
    HearthflameMask,
    HeatRock,
    HeavyBall,
    HeavyDutyBoots,
    HondewBerry,

    // I items
    IapapaBerry,
    IceStone,
    IciclePlate,
    IcyRock,
    InsectPlate,
    IronBall,
    IronPlate,

    // J items
    JabocaBerry,

    // K items
    KasibBerry,
    KebiaBerry,
    KeeBerry,
    KelpsyBerry,
    KingsRock,

    // L items
    LaggingTail,
    LansatBerry,
    LaxIncense,
    LeafStone,
    Leek,
    Leftovers,
    LeppaBerry,
    LevelBall,
    LiechiBerry,
    LifeOrb,
    LightBall,
    LightClay,
    LoadedDice,
    LoveBall,
    LoveSweet,
    LuckyPunch,
    LumBerry,
    LuminousMoss,
    LureBall,
    LustrousGlobe,
    LustrousOrb,
    LuxuryBall,

    // M items
    Magnet,
    MagoBerry,
    MarangaBerry,
    MasterBall,
    MasterpieceTeacup,
    MeadowPlate,
    MentalHerb,
    MetalAlloy,
    MetalCoat,
    MetalPowder,
    Metronome,
    MicleBerry,
    MindPlate,
    MiracleSeed,
    MirrorHerb,
    MistySeed,
    MoonBall,
    MoonStone,
    MuscleBand,
    MysticWater,

    // N items
    NanabBerry,
    NestBall,
    NetBall,
    NeverMeltIce,
    NomelBerry,
    NormalGem,

    // O items
    OccaBerry,
    OddIncense,
    OvalStone,

    // P items
    PamtreBerry,
    ParkBall,
    PasshoBerry,
    PayapaBerry,
    PechaBerry,
    PersimBerry,
    PetayaBerry,
    PinapBerry,
    PixiePlate,
    PlumeFossil,
    PoisonBarb,
    PokeBall,
    PomegBerry,
    PowerAnklet,
    PowerBand,
    PowerBelt,
    PowerBracer,
    PowerLens,
    PowerWeight,
    PremierBall,
    PrettyFeather,
    PrismScale,
    Protector,
    PsychicSeed,
    PunchingGlove,

    // Q items
    QualotBerry,
    QuickBall,
    QuickClaw,
    QuickPowder,

    // R items
    RabutaBerry,
    RareBone,
    RawstBerry,
    RazorClaw,
    RazorFang,
    ReaperCloth,
    ReBattle,
    RedCard,
    RepeatBall,
    RibbonSweet,
    RindoBerry,
    RingTarget,
    RootFossil,
    RoseIncense,
    RoseliaBerry,

    // S items
    SafariBall,
    SafetyGoggles,
    SailFossil,
    SalacBerry,
    ScopeLens,
    SeaIncense,
    SharpBeak,
    ShedShell,
    ShellBell,
    ShinyStone,
    ShucaBerry,
    SilkScarf,
    SilverPowder,
    SkyPlate,
    Snowball,
    SoftSand,
    SoulDew,
    SpellTag,
    SpelonBerry,
    SplashPlate,
    SpookyPlate,
    SportBall,
    StarfBerry,
    StarSweet,
    Stick,
    StonePlate,
    StrangeBall,
    StrawberrySweet,
    SunStone,
    SweetApple,
    SyrupyApple,

    // T items
    TamatoBerry,
    TangaBerry,
    TartApple,
    ThickClub,
    ThroatSpray,
    ThunderStone,
    TimerBall,
    ToxicPlate,
    TwistedSpoon,

    // U items
    UltraBall,
    UpGrade,

    StickyBarb,

    // V items - none for Gen 9 standard

    // W items
    WacanBerry,
    WaterStone,
    WeaknessPolicy,
    WellspringMask,
    WhiteHerb,
    WideLens,
    WikiBerry,
    WiseGlasses,

    // X items - none for Gen 9 standard

    // Y items
    YacheBerry,

    // Z items
    ZapPlate,
    ZoomLens,

    BoosterEnergy,
    ToxicOrb,
    TerrainExtender,
    ProtectivePads,

    EnigmaBerry,
    FigyBerry,
    SitrusBerry,
    OranBerry,
    BerryJuice,
    RustedSword,
    RustedShield,
    PowerHerb,
    RowapBerry,
    BlunderPolicy,
    UtilityUmbrella,

    // Mega Stones
    Sablenite,
    Mawilite,
    Aggronite,
    Medichamite,
    Manectite,
    Sharpedonite,
    Cameruptite,
    Altarianite,
    Banettite,
    Absolite,
    Glalitite,
    Salamencite,
    Metagrossite,
    Latiasite,
    Latiosite,

    // Gen 6 Mega Stones
    Chesnaughtite,
    Delphoxite,
    Greninjite,
    Pyroarite,
    Floettite,
    Malamarite,
    Barbaracite,
    Dragalgite,

    // Primal Orbs
    BlueOrb,
    RedOrb,

    // Ogerpon Masks (already defined above in W section, so commenting out duplicate)
    // WellspringMask,

    // Weather extending rocks
    SmoothRock,

    None,
}