namespace ApogeeVGC.Sim.Items;

public enum ItemId
{
    Leftovers,
    ChoiceSpecs,
    FlameOrb,
    RockyHelmet,
    LightClay,
    AssaultVest,
    AbilityShield,
    AbsorbBulb,
    AdamantCrystal,
    AdamantOrb,
    AdrenalineOrb,
    AguavBerry,
    AirBalloon,
    ApicotBerry,
    AspearBerry,
    AuspiciousArmor,

    // B items
    BabiriBerry,
    BeastBall,
    BerrySweet,
    BigNugget,
    BigRoot,
    BindingBand,
    BlackBelt,
    BlackGlasses,
    BlackSludge,
    BottleCap,
    BrightPowder,

    // C items
    CellBattery,
    Charcoal,
    ChartiBerry,
    CheriBerry,
    ChestoBerry,
    ChilanBerry,
    ChoiceBand,
    ChoiceScarf,
    ChopleBerry,
    ClearAmulet,
    CobaBerry,
    ColburBerry,
    CornerstoneMask,
    CovertCloak,
    CrackedPot,
    CustapBerry,

    // D items
    DampRock,
    DawnStone,
    DeepSeaScale,
    DeepSeaTooth,
    DestinyKnot,
    DiveBall,
    DracoPlate,
    DragonFang,
    DragonScale,
    DreadPlate,
    DreamBall,
    DubiousDisc,
    DuskBall,
    DuskStone,

    // E items
    EarthPlate,
    EjectButton,
    EjectPack,
    Electirizer,
    ElectricSeed,
    Eviolite,
    ExpertBelt,

    StickyBarb,

    BoosterEnergy,
    ToxicOrb,
    TerrainExtender,
    IronBall,
    ProtectivePads,

        LeppaBerry,
        EnigmaBerry,
        FigyBerry,
        IapapaBerry,
        MagoBerry,
        SitrusBerry,
        WikiBerry,
        OranBerry,
        BerryJuice,
        RustedSword,
        RustedShield,
        PowerHerb,
        JabocaBerry,
        RowapBerry,
        RedCard,
        UtilityUmbrella,
        BlunderPolicy,
        LoadedDice,

        // Mega Stones
        Sablenite,
        Mawilite,
        Aggronite,
        Medichamite,
        Manectite,
        Sharpedonite,
        Cameruptite,
        Altarianite,
        Banettite,
        Absolite,
        Glalitite,
        Salamencite,
        Metagrossite,
        Latiasite,
        Latiosite,

        // Gen 6 Mega Stones
        Chesnaughtite,
        Delphoxite,
        Greninjite,
        Pyroarite,
        Floettite,
        Malamarite,
        Barbaracite,
        Dragalgite,

        // Primal Orbs
        BlueOrb,
        RedOrb,

        // Ogerpon Masks
        WellspringMask,
        HearthflameMask,

        // Weather extending rocks
        IcyRock,
        SmoothRock,
        HeatRock,

        None,
    }