namespace ApogeeVGC.Sim.SpeciesClasses;

public enum FormeId
{
    Ice,
    Mega,
    MegaX,
    MegaY,
            Gmax,
            Alola,
            AlolaTotem,
            Cosplay,
            RockStar,
            Belle,
            PopStar,
            PhD,
            Libre,
            Original,
            Hoenn,
            Sinnoh,
            Unova,
            Kalos,
            Partner,
            Starter,
            World,
                Galar,
                Hisui,
                PaldeaCombat,
                PaldeaBlaze,
                PaldeaAqua,
                None,
            }
