namespace ApogeeVGC.Sim.SpeciesClasses;

public enum FormeId
{
    Ice,
    Mega,
    MegaX,
    MegaY,
    Gmax,
    Alola,
    AlolaTotem,
    Cosplay,
    RockStar,
    Belle,
    PopStar,
    PhD,
    Libre,
    Original,
    Hoenn,
    Sinnoh,
    Unova,
    Kalos,
    Partner,
    Starter,
    World,
    Galar,
    Hisui,
    PaldeaCombat,
    PaldeaBlaze,
    PaldeaAqua,
    Paldea,
    SpikyEared,
    Sunny,
    Rainy,
    Snowy,
    Primal,
    Attack,
    Defense,
    Speed,
    Sandy,
    Trash,
    Sunshine,
    Heat,
    Wash,
    Frost,
    Fan,
    Mow,
        Origin,
        Sky,
        Altered,
        Land,
        None,

                    // Type formes (Arceus)
                    Bug,
                    Dark,
                    Dragon,
                    Electric,
                    Fairy,
                    Fighting,
                    Fire,
                    Flying,
                    Ghost,
                    Grass,
                    Ground,
                    Poison,
                    Psychic,
                    Rock,
                    Steel,
                    Water,

                        // Striped formes (Basculin)
                        BlueStriped,
                        WhiteStriped,

                        // Darmanitan formes
                        Standard,
                        Zen,
                        GalarZen,
                    }