namespace ApogeeVGC.Sim.SpeciesClasses;

public enum SpecieId
{
    Bulbasaur,
    Ivysaur,
    Venusaur,
    VenusaurMega,
    Charmander,
    Charmeleon,
    Charizard,
    CharizardMegaX,
    CharizardMegaY,
    CharizardGmax,
    Squirtle,
    Wartortle,
    Blastoise,
    BlastoiseMega,

    CalyrexIce,
    Miraidon,
    Ursaluna,
    Volcarona,
    Grimmsnarl,
    IronHands,

    Calyrex,
    ShayminSky,
    Shaymin,
    GreninjaBond,
    RockruffDusk,
    TerapagosTerastal,
    TerapagosStellar,
    Zacian,
    ZacianCrowned,
    Zamazenta,
    ZamazentaCrowned,
    Ogerpon,
    OgerponTealtera,
    Terapagos,
    EternatusEternamax,
    Morpeko,
    Xerneas,
    XerneasNeutral,
    XerneasActive,
}
