// This file has been split into individual union type files.
// All specific union types have been extracted to separate files in this directory:
// - OnFractionalPriority.cs
// - OnCriticalHit.cs
// - OnTryHeal.cs
// - OnFlinch.cs
// - OnLockMove.cs
// - SparseBoostsTableVoidUnion.cs
// - OnNegateImmunity.cs
// - OnTakeItem.cs
// - SingleEventTarget.cs
// - SingleEventSource.cs
// - RunEventSource.cs
// - RelayVar.cs
// - RunEventTarget.cs
// - EffectStateId.cs
// - EventTargetParameter.cs
// - EventSourceParameter.cs
// - ItemBoosts.cs
// - OnItemEatUse.cs
// - OnTryEatItem.cs
// - MoveDamage.cs
// - MoveOhko.cs
// - MoveSelfSwitch.cs
// - MoveSelfDestruct.cs
// - MoveIgnoreImmunity.cs
// - SpecieUnreleasedHidden.cs
// - BattleDamageEffect.cs
// - BattleHealEffect.cs
// - EffectStateTarget.cs
// - EffectHolder.cs
// - EffectDelegate.cs
// - FormatHasValue.cs
// - Part.cs
// - PartFuncUnion.cs
// - HpColor.cs
// - Secret.cs
// - Shared.cs
// - SideSecretSharedResult.cs
